/*
 * (C) Datadog, Inc. 2019
 * All rights reserved
 * Licensed under a 3-clause BSD style license (see LICENSE)
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.client.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.datadog.api.client.v1.model.ApiKey;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse200
 */

public class InlineResponse200 {
  public static final String JSON_PROPERTY_API_KEYS = "api_keys";
  private List<ApiKey> apiKeys = null;


  public InlineResponse200 apiKeys(List<ApiKey> apiKeys) {
    
    this.apiKeys = apiKeys;
    return this;
  }

  public InlineResponse200 addApiKeysItem(ApiKey apiKeysItem) {
    if (this.apiKeys == null) {
      this.apiKeys = new ArrayList<ApiKey>();
    }
    this.apiKeys.add(apiKeysItem);
    return this;
  }

   /**
   * Get apiKeys
   * @return apiKeys
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"created\":\"2019-08-02 15:31:06\",\"created_by\":\"example.com\",\"key\":\"1234512345123456abcabc912349abcd\",\"name\":\"example user\"},{\"created\":\"2019-08-02 15:31:07\",\"created_by\":\"example2.com\",\"key\":\"1234512345123456abcabc912349abcd\",\"name\":\"example user 2\"},{\"created\":\"2019-08-02 15:31:07\",\"created_by\":\"example3.com\",\"key\":\"1234512345123456abcabc912349abcd\",\"name\":\"example user 3\"}]", value = "")
  @JsonProperty(JSON_PROPERTY_API_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ApiKey> getApiKeys() {
    return apiKeys;
  }



  public void setApiKeys(List<ApiKey> apiKeys) {
    this.apiKeys = apiKeys;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.apiKeys, inlineResponse200.apiKeys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKeys);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    sb.append("    apiKeys: ").append(toIndentedString(apiKeys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

