/*
 * (C) Datadog, Inc. 2019
 * All rights reserved
 * Licensed under a 3-clause BSD style license (see LICENSE)
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.client.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.datadog.api.client.v1.model.ApplicationKey;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2002
 */

public class InlineResponse2002 {
  public static final String JSON_PROPERTY_APPLICATION_KEYS = "application_keys";
  private List<ApplicationKey> applicationKeys = null;


  public InlineResponse2002 applicationKeys(List<ApplicationKey> applicationKeys) {
    
    this.applicationKeys = applicationKeys;
    return this;
  }

  public InlineResponse2002 addApplicationKeysItem(ApplicationKey applicationKeysItem) {
    if (this.applicationKeys == null) {
      this.applicationKeys = new ArrayList<ApplicationKey>();
    }
    this.applicationKeys.add(applicationKeysItem);
    return this;
  }

   /**
   * Get applicationKeys
   * @return applicationKeys
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"hash\":\"1234512345123459cda4eb9ced49a3d84fd0138c\",\"name\":\"example user1\",\"owner\":\"example.com\"},{\"hash\":\"1234512345123459cda4eb9ced49a3d84fd0138c\",\"name\":\"example user2\",\"owner\":\"example2.com\"},{\"hash\":\"1234512345123459cda4eb9ced49a3d84fd0138c\",\"name\":\"example user3\",\"owner\":\"example3.com\"}]", value = "")
  @JsonProperty(JSON_PROPERTY_APPLICATION_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ApplicationKey> getApplicationKeys() {
    return applicationKeys;
  }



  public void setApplicationKeys(List<ApplicationKey> applicationKeys) {
    this.applicationKeys = applicationKeys;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.applicationKeys, inlineResponse2002.applicationKeys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationKeys);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    sb.append("    applicationKeys: ").append(toIndentedString(applicationKeys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

