/*
 * (C) Datadog, Inc. 2019
 * All rights reserved
 * Licensed under a 3-clause BSD style license (see LICENSE)
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.client.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.datadog.api.client.v1.model.OrgSettingsSaml;
import com.datadog.api.client.v1.model.OrgSettingsSamlAutocreateUsersDomains;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * OrgSettingsUpdateBody
 */

public class OrgSettingsUpdateBody {
  public static final String JSON_PROPERTY_SAML = "saml";
  private OrgSettingsSaml saml;

  public static final String JSON_PROPERTY_SAML_AUTOCREATE_USERS_DOMAINS = "saml_autocreate_users_domains";
  private OrgSettingsSamlAutocreateUsersDomains samlAutocreateUsersDomains;

  public static final String JSON_PROPERTY_SAML_IDP_INITIATED_LOGIN = "saml_idp_initiated_login";
  private OrgSettingsSaml samlIdpInitiatedLogin;

  public static final String JSON_PROPERTY_SAML_STRICT_MODE = "saml_strict_mode";
  private OrgSettingsSaml samlStrictMode;


  public OrgSettingsUpdateBody saml(OrgSettingsSaml saml) {
    
    this.saml = saml;
    return this;
  }

   /**
   * Get saml
   * @return saml
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SAML)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrgSettingsSaml getSaml() {
    return saml;
  }



  public void setSaml(OrgSettingsSaml saml) {
    this.saml = saml;
  }


  public OrgSettingsUpdateBody samlAutocreateUsersDomains(OrgSettingsSamlAutocreateUsersDomains samlAutocreateUsersDomains) {
    
    this.samlAutocreateUsersDomains = samlAutocreateUsersDomains;
    return this;
  }

   /**
   * Get samlAutocreateUsersDomains
   * @return samlAutocreateUsersDomains
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SAML_AUTOCREATE_USERS_DOMAINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrgSettingsSamlAutocreateUsersDomains getSamlAutocreateUsersDomains() {
    return samlAutocreateUsersDomains;
  }



  public void setSamlAutocreateUsersDomains(OrgSettingsSamlAutocreateUsersDomains samlAutocreateUsersDomains) {
    this.samlAutocreateUsersDomains = samlAutocreateUsersDomains;
  }


  public OrgSettingsUpdateBody samlIdpInitiatedLogin(OrgSettingsSaml samlIdpInitiatedLogin) {
    
    this.samlIdpInitiatedLogin = samlIdpInitiatedLogin;
    return this;
  }

   /**
   * Get samlIdpInitiatedLogin
   * @return samlIdpInitiatedLogin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SAML_IDP_INITIATED_LOGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrgSettingsSaml getSamlIdpInitiatedLogin() {
    return samlIdpInitiatedLogin;
  }



  public void setSamlIdpInitiatedLogin(OrgSettingsSaml samlIdpInitiatedLogin) {
    this.samlIdpInitiatedLogin = samlIdpInitiatedLogin;
  }


  public OrgSettingsUpdateBody samlStrictMode(OrgSettingsSaml samlStrictMode) {
    
    this.samlStrictMode = samlStrictMode;
    return this;
  }

   /**
   * Get samlStrictMode
   * @return samlStrictMode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SAML_STRICT_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrgSettingsSaml getSamlStrictMode() {
    return samlStrictMode;
  }



  public void setSamlStrictMode(OrgSettingsSaml samlStrictMode) {
    this.samlStrictMode = samlStrictMode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgSettingsUpdateBody orgSettingsUpdateBody = (OrgSettingsUpdateBody) o;
    return Objects.equals(this.saml, orgSettingsUpdateBody.saml) &&
        Objects.equals(this.samlAutocreateUsersDomains, orgSettingsUpdateBody.samlAutocreateUsersDomains) &&
        Objects.equals(this.samlIdpInitiatedLogin, orgSettingsUpdateBody.samlIdpInitiatedLogin) &&
        Objects.equals(this.samlStrictMode, orgSettingsUpdateBody.samlStrictMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saml, samlAutocreateUsersDomains, samlIdpInitiatedLogin, samlStrictMode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgSettingsUpdateBody {\n");
    sb.append("    saml: ").append(toIndentedString(saml)).append("\n");
    sb.append("    samlAutocreateUsersDomains: ").append(toIndentedString(samlAutocreateUsersDomains)).append("\n");
    sb.append("    samlIdpInitiatedLogin: ").append(toIndentedString(samlIdpInitiatedLogin)).append("\n");
    sb.append("    samlStrictMode: ").append(toIndentedString(samlStrictMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

