/*
 * (C) Datadog, Inc. 2019
 * All rights reserved
 * Licensed under a 3-clause BSD style license (see LICENSE)
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.client.v1.model;

import com.datadog.api.client.v1.model.ApplicationKey;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2002
 */
public class InlineResponse2002Test {
    private final InlineResponse2002 model = new InlineResponse2002();

    /**
     * Model tests for InlineResponse2002
     */
    @Test
    public void testInlineResponse2002() {
        // TODO: test InlineResponse2002
    }

    /**
     * Test the property 'applicationKeys'
     */
    @Test
    public void applicationKeysTest() {
        // TODO: test applicationKeys
    }

}
