/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.datadog.api.v1.client.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

/** Response with hourly report of all data billed by Datadog all organizations. */
@ApiModel(
    description = "Response with hourly report of all data billed by Datadog all organizations.")
@JsonPropertyOrder({
  UsageSummaryResponse.JSON_PROPERTY_AGENT_HOST_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_APM_AZURE_APP_SERVICE_HOST_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_APM_HOST_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_AWS_HOST_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_AWS_LAMBDA_FUNC_COUNT,
  UsageSummaryResponse.JSON_PROPERTY_AWS_LAMBDA_INVOCATIONS_SUM,
  UsageSummaryResponse.JSON_PROPERTY_AZURE_APP_SERVICE_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_AZURE_HOST_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_BILLABLE_INGESTED_BYTES_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_COMPLIANCE_CONTAINER_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_COMPLIANCE_HOST_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_CONTAINER_AVG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_CONTAINER_HWM_SUM,
  UsageSummaryResponse.JSON_PROPERTY_CUSTOM_TS_SUM,
  UsageSummaryResponse.JSON_PROPERTY_END_DATE,
  UsageSummaryResponse.JSON_PROPERTY_FARGATE_TASKS_COUNT_AVG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_FARGATE_TASKS_COUNT_HWM_SUM,
  UsageSummaryResponse.JSON_PROPERTY_GCP_HOST_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_HEROKU_HOST_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_INCIDENT_MANAGEMENT_MONTHLY_ACTIVE_USERS_HWM_SUM,
  UsageSummaryResponse.JSON_PROPERTY_INDEXED_EVENTS_COUNT_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_INFRA_HOST_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_INGESTED_EVENTS_BYTES_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_IOT_DEVICE_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_IOT_DEVICE_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_LAST_UPDATED,
  UsageSummaryResponse.JSON_PROPERTY_LIVE_INDEXED_EVENTS_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_LIVE_INGESTED_BYTES_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_ANDROID_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_IOS_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_NETFLOW_INDEXED_EVENTS_COUNT_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_NPM_HOST_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_OPENTELEMETRY_HOST_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_PROFILING_CONTAINER_AGENT_COUNT_AVG,
  UsageSummaryResponse.JSON_PROPERTY_PROFILING_HOST_COUNT_TOP99P_SUM,
  UsageSummaryResponse.JSON_PROPERTY_REHYDRATED_INDEXED_EVENTS_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_REHYDRATED_INGESTED_BYTES_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_RUM_SESSION_COUNT_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_RUM_TOTAL_SESSION_COUNT_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_START_DATE,
  UsageSummaryResponse.JSON_PROPERTY_SYNTHETICS_BROWSER_CHECK_CALLS_COUNT_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_SYNTHETICS_CHECK_CALLS_COUNT_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_TRACE_SEARCH_INDEXED_EVENTS_COUNT_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_TWOL_INGESTED_EVENTS_BYTES_AGG_SUM,
  UsageSummaryResponse.JSON_PROPERTY_USAGE,
  UsageSummaryResponse.JSON_PROPERTY_VSPHERE_HOST_TOP99P_SUM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UsageSummaryResponse {
  public static final String JSON_PROPERTY_AGENT_HOST_TOP99P_SUM = "agent_host_top99p_sum";
  private JsonNullable<Long> agentHostTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_APM_AZURE_APP_SERVICE_HOST_TOP99P_SUM =
      "apm_azure_app_service_host_top99p_sum";
  private JsonNullable<Long> apmAzureAppServiceHostTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_APM_HOST_TOP99P_SUM = "apm_host_top99p_sum";
  private JsonNullable<Long> apmHostTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_AWS_HOST_TOP99P_SUM = "aws_host_top99p_sum";
  private JsonNullable<Long> awsHostTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_AWS_LAMBDA_FUNC_COUNT = "aws_lambda_func_count";
  private JsonNullable<Long> awsLambdaFuncCount = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_AWS_LAMBDA_INVOCATIONS_SUM =
      "aws_lambda_invocations_sum";
  private JsonNullable<Long> awsLambdaInvocationsSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_AZURE_APP_SERVICE_TOP99P_SUM =
      "azure_app_service_top99p_sum";
  private JsonNullable<Long> azureAppServiceTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_AZURE_HOST_TOP99P_SUM = "azure_host_top99p_sum";
  private JsonNullable<Long> azureHostTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_BILLABLE_INGESTED_BYTES_AGG_SUM =
      "billable_ingested_bytes_agg_sum";
  private JsonNullable<Long> billableIngestedBytesAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_COMPLIANCE_CONTAINER_AGG_SUM =
      "compliance_container_agg_sum";
  private JsonNullable<Long> complianceContainerAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_COMPLIANCE_HOST_AGG_SUM = "compliance_host_agg_sum";
  private JsonNullable<Long> complianceHostAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_CONTAINER_AVG_SUM = "container_avg_sum";
  private JsonNullable<Long> containerAvgSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_CONTAINER_HWM_SUM = "container_hwm_sum";
  private JsonNullable<Long> containerHwmSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_CUSTOM_TS_SUM = "custom_ts_sum";
  private JsonNullable<Long> customTsSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_END_DATE = "end_date";
  private OffsetDateTime endDate;

  public static final String JSON_PROPERTY_FARGATE_TASKS_COUNT_AVG_SUM =
      "fargate_tasks_count_avg_sum";
  private JsonNullable<Long> fargateTasksCountAvgSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_FARGATE_TASKS_COUNT_HWM_SUM =
      "fargate_tasks_count_hwm_sum";
  private JsonNullable<Long> fargateTasksCountHwmSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_GCP_HOST_TOP99P_SUM = "gcp_host_top99p_sum";
  private JsonNullable<Long> gcpHostTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_HEROKU_HOST_TOP99P_SUM = "heroku_host_top99p_sum";
  private JsonNullable<Long> herokuHostTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_INCIDENT_MANAGEMENT_MONTHLY_ACTIVE_USERS_HWM_SUM =
      "incident_management_monthly_active_users_hwm_sum";
  private JsonNullable<Long> incidentManagementMonthlyActiveUsersHwmSum =
      JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_INDEXED_EVENTS_COUNT_AGG_SUM =
      "indexed_events_count_agg_sum";
  private JsonNullable<Long> indexedEventsCountAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_INFRA_HOST_TOP99P_SUM = "infra_host_top99p_sum";
  private JsonNullable<Long> infraHostTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_INGESTED_EVENTS_BYTES_AGG_SUM =
      "ingested_events_bytes_agg_sum";
  private JsonNullable<Long> ingestedEventsBytesAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_IOT_DEVICE_AGG_SUM = "iot_device_agg_sum";
  private JsonNullable<Long> iotDeviceAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_IOT_DEVICE_TOP99P_SUM = "iot_device_top99p_sum";
  private JsonNullable<Long> iotDeviceTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_LAST_UPDATED = "last_updated";
  private OffsetDateTime lastUpdated;

  public static final String JSON_PROPERTY_LIVE_INDEXED_EVENTS_AGG_SUM =
      "live_indexed_events_agg_sum";
  private JsonNullable<Long> liveIndexedEventsAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_LIVE_INGESTED_BYTES_AGG_SUM =
      "live_ingested_bytes_agg_sum";
  private JsonNullable<Long> liveIngestedBytesAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_AGG_SUM =
      "mobile_rum_session_count_agg_sum";
  private JsonNullable<Long> mobileRumSessionCountAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_ANDROID_AGG_SUM =
      "mobile_rum_session_count_android_agg_sum";
  private JsonNullable<Long> mobileRumSessionCountAndroidAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_IOS_AGG_SUM =
      "mobile_rum_session_count_ios_agg_sum";
  private JsonNullable<Long> mobileRumSessionCountIosAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_NETFLOW_INDEXED_EVENTS_COUNT_AGG_SUM =
      "netflow_indexed_events_count_agg_sum";
  private JsonNullable<Long> netflowIndexedEventsCountAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_NPM_HOST_TOP99P_SUM = "npm_host_top99p_sum";
  private JsonNullable<Long> npmHostTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_OPENTELEMETRY_HOST_TOP99P_SUM =
      "opentelemetry_host_top99p_sum";
  private JsonNullable<Long> opentelemetryHostTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_PROFILING_CONTAINER_AGENT_COUNT_AVG =
      "profiling_container_agent_count_avg";
  private JsonNullable<Long> profilingContainerAgentCountAvg = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_PROFILING_HOST_COUNT_TOP99P_SUM =
      "profiling_host_count_top99p_sum";
  private JsonNullable<Long> profilingHostCountTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_REHYDRATED_INDEXED_EVENTS_AGG_SUM =
      "rehydrated_indexed_events_agg_sum";
  private JsonNullable<Long> rehydratedIndexedEventsAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_REHYDRATED_INGESTED_BYTES_AGG_SUM =
      "rehydrated_ingested_bytes_agg_sum";
  private JsonNullable<Long> rehydratedIngestedBytesAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_RUM_SESSION_COUNT_AGG_SUM = "rum_session_count_agg_sum";
  private JsonNullable<Long> rumSessionCountAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_RUM_TOTAL_SESSION_COUNT_AGG_SUM =
      "rum_total_session_count_agg_sum";
  private JsonNullable<Long> rumTotalSessionCountAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_START_DATE = "start_date";
  private OffsetDateTime startDate;

  public static final String JSON_PROPERTY_SYNTHETICS_BROWSER_CHECK_CALLS_COUNT_AGG_SUM =
      "synthetics_browser_check_calls_count_agg_sum";
  private JsonNullable<Long> syntheticsBrowserCheckCallsCountAggSum =
      JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_SYNTHETICS_CHECK_CALLS_COUNT_AGG_SUM =
      "synthetics_check_calls_count_agg_sum";
  private JsonNullable<Long> syntheticsCheckCallsCountAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_TRACE_SEARCH_INDEXED_EVENTS_COUNT_AGG_SUM =
      "trace_search_indexed_events_count_agg_sum";
  private JsonNullable<Long> traceSearchIndexedEventsCountAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_TWOL_INGESTED_EVENTS_BYTES_AGG_SUM =
      "twol_ingested_events_bytes_agg_sum";
  private JsonNullable<Long> twolIngestedEventsBytesAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_USAGE = "usage";
  private List<UsageSummaryDate> usage = null;

  public static final String JSON_PROPERTY_VSPHERE_HOST_TOP99P_SUM = "vsphere_host_top99p_sum";
  private JsonNullable<Long> vsphereHostTop99pSum = JsonNullable.<Long>undefined();

  public UsageSummaryResponse agentHostTop99pSum(Long agentHostTop99pSum) {
    this.agentHostTop99pSum = JsonNullable.<Long>of(agentHostTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all agent hosts over all hours in the current months for all
   * organizations.
   *
   * @return agentHostTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all agent hosts over all hours in the current months for"
              + " all organizations.")
  @JsonIgnore
  public Long getAgentHostTop99pSum() {
    return agentHostTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AGENT_HOST_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getAgentHostTop99pSum_JsonNullable() {
    return agentHostTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_AGENT_HOST_TOP99P_SUM)
  public void setAgentHostTop99pSum_JsonNullable(JsonNullable<Long> agentHostTop99pSum) {
    this.agentHostTop99pSum = agentHostTop99pSum;
  }

  public void setAgentHostTop99pSum(Long agentHostTop99pSum) {
    this.agentHostTop99pSum = JsonNullable.<Long>of(agentHostTop99pSum);
  }

  public UsageSummaryResponse apmAzureAppServiceHostTop99pSum(
      Long apmAzureAppServiceHostTop99pSum) {
    this.apmAzureAppServiceHostTop99pSum = JsonNullable.<Long>of(apmAzureAppServiceHostTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all Azure app services using APM over all hours in the current
   * months all organizations.
   *
   * @return apmAzureAppServiceHostTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all Azure app services using APM over all hours in the"
              + " current months all organizations.")
  @JsonIgnore
  public Long getApmAzureAppServiceHostTop99pSum() {
    return apmAzureAppServiceHostTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_APM_AZURE_APP_SERVICE_HOST_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getApmAzureAppServiceHostTop99pSum_JsonNullable() {
    return apmAzureAppServiceHostTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_APM_AZURE_APP_SERVICE_HOST_TOP99P_SUM)
  public void setApmAzureAppServiceHostTop99pSum_JsonNullable(
      JsonNullable<Long> apmAzureAppServiceHostTop99pSum) {
    this.apmAzureAppServiceHostTop99pSum = apmAzureAppServiceHostTop99pSum;
  }

  public void setApmAzureAppServiceHostTop99pSum(Long apmAzureAppServiceHostTop99pSum) {
    this.apmAzureAppServiceHostTop99pSum = JsonNullable.<Long>of(apmAzureAppServiceHostTop99pSum);
  }

  public UsageSummaryResponse apmHostTop99pSum(Long apmHostTop99pSum) {
    this.apmHostTop99pSum = JsonNullable.<Long>of(apmHostTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all distinct APM hosts over all hours in the current months for
   * all organizations.
   *
   * @return apmHostTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all distinct APM hosts over all hours in the current"
              + " months for all organizations.")
  @JsonIgnore
  public Long getApmHostTop99pSum() {
    return apmHostTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_APM_HOST_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getApmHostTop99pSum_JsonNullable() {
    return apmHostTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_APM_HOST_TOP99P_SUM)
  public void setApmHostTop99pSum_JsonNullable(JsonNullable<Long> apmHostTop99pSum) {
    this.apmHostTop99pSum = apmHostTop99pSum;
  }

  public void setApmHostTop99pSum(Long apmHostTop99pSum) {
    this.apmHostTop99pSum = JsonNullable.<Long>of(apmHostTop99pSum);
  }

  public UsageSummaryResponse awsHostTop99pSum(Long awsHostTop99pSum) {
    this.awsHostTop99pSum = JsonNullable.<Long>of(awsHostTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all AWS hosts over all hours in the current months for all
   * organizations.
   *
   * @return awsHostTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all AWS hosts over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getAwsHostTop99pSum() {
    return awsHostTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AWS_HOST_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getAwsHostTop99pSum_JsonNullable() {
    return awsHostTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_AWS_HOST_TOP99P_SUM)
  public void setAwsHostTop99pSum_JsonNullable(JsonNullable<Long> awsHostTop99pSum) {
    this.awsHostTop99pSum = awsHostTop99pSum;
  }

  public void setAwsHostTop99pSum(Long awsHostTop99pSum) {
    this.awsHostTop99pSum = JsonNullable.<Long>of(awsHostTop99pSum);
  }

  public UsageSummaryResponse awsLambdaFuncCount(Long awsLambdaFuncCount) {
    this.awsLambdaFuncCount = JsonNullable.<Long>of(awsLambdaFuncCount);
    return this;
  }

  /**
   * Shows the average of the number of functions that executed 1 or more times each hour in the
   * current months for all organizations.
   *
   * @return awsLambdaFuncCount
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the average of the number of functions that executed 1 or more times each hour in"
              + " the current months for all organizations.")
  @JsonIgnore
  public Long getAwsLambdaFuncCount() {
    return awsLambdaFuncCount.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AWS_LAMBDA_FUNC_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getAwsLambdaFuncCount_JsonNullable() {
    return awsLambdaFuncCount;
  }

  @JsonProperty(JSON_PROPERTY_AWS_LAMBDA_FUNC_COUNT)
  public void setAwsLambdaFuncCount_JsonNullable(JsonNullable<Long> awsLambdaFuncCount) {
    this.awsLambdaFuncCount = awsLambdaFuncCount;
  }

  public void setAwsLambdaFuncCount(Long awsLambdaFuncCount) {
    this.awsLambdaFuncCount = JsonNullable.<Long>of(awsLambdaFuncCount);
  }

  public UsageSummaryResponse awsLambdaInvocationsSum(Long awsLambdaInvocationsSum) {
    this.awsLambdaInvocationsSum = JsonNullable.<Long>of(awsLambdaInvocationsSum);
    return this;
  }

  /**
   * Shows the sum of all AWS Lambda invocations over all hours in the current months for all
   * organizations.
   *
   * @return awsLambdaInvocationsSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all AWS Lambda invocations over all hours in the current months for"
              + " all organizations.")
  @JsonIgnore
  public Long getAwsLambdaInvocationsSum() {
    return awsLambdaInvocationsSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AWS_LAMBDA_INVOCATIONS_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getAwsLambdaInvocationsSum_JsonNullable() {
    return awsLambdaInvocationsSum;
  }

  @JsonProperty(JSON_PROPERTY_AWS_LAMBDA_INVOCATIONS_SUM)
  public void setAwsLambdaInvocationsSum_JsonNullable(JsonNullable<Long> awsLambdaInvocationsSum) {
    this.awsLambdaInvocationsSum = awsLambdaInvocationsSum;
  }

  public void setAwsLambdaInvocationsSum(Long awsLambdaInvocationsSum) {
    this.awsLambdaInvocationsSum = JsonNullable.<Long>of(awsLambdaInvocationsSum);
  }

  public UsageSummaryResponse azureAppServiceTop99pSum(Long azureAppServiceTop99pSum) {
    this.azureAppServiceTop99pSum = JsonNullable.<Long>of(azureAppServiceTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all Azure app services over all hours in the current months for
   * all organizations.
   *
   * @return azureAppServiceTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all Azure app services over all hours in the current"
              + " months for all organizations.")
  @JsonIgnore
  public Long getAzureAppServiceTop99pSum() {
    return azureAppServiceTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AZURE_APP_SERVICE_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getAzureAppServiceTop99pSum_JsonNullable() {
    return azureAppServiceTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_AZURE_APP_SERVICE_TOP99P_SUM)
  public void setAzureAppServiceTop99pSum_JsonNullable(
      JsonNullable<Long> azureAppServiceTop99pSum) {
    this.azureAppServiceTop99pSum = azureAppServiceTop99pSum;
  }

  public void setAzureAppServiceTop99pSum(Long azureAppServiceTop99pSum) {
    this.azureAppServiceTop99pSum = JsonNullable.<Long>of(azureAppServiceTop99pSum);
  }

  public UsageSummaryResponse azureHostTop99pSum(Long azureHostTop99pSum) {
    this.azureHostTop99pSum = JsonNullable.<Long>of(azureHostTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all Azure hosts over all hours in the current months for all
   * organizations.
   *
   * @return azureHostTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all Azure hosts over all hours in the current months for"
              + " all organizations.")
  @JsonIgnore
  public Long getAzureHostTop99pSum() {
    return azureHostTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AZURE_HOST_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getAzureHostTop99pSum_JsonNullable() {
    return azureHostTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_AZURE_HOST_TOP99P_SUM)
  public void setAzureHostTop99pSum_JsonNullable(JsonNullable<Long> azureHostTop99pSum) {
    this.azureHostTop99pSum = azureHostTop99pSum;
  }

  public void setAzureHostTop99pSum(Long azureHostTop99pSum) {
    this.azureHostTop99pSum = JsonNullable.<Long>of(azureHostTop99pSum);
  }

  public UsageSummaryResponse billableIngestedBytesAggSum(Long billableIngestedBytesAggSum) {
    this.billableIngestedBytesAggSum = JsonNullable.<Long>of(billableIngestedBytesAggSum);
    return this;
  }

  /**
   * Shows the sum of all log bytes ingested over all hours in the current months for all
   * organizations.
   *
   * @return billableIngestedBytesAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all log bytes ingested over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getBillableIngestedBytesAggSum() {
    return billableIngestedBytesAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_BILLABLE_INGESTED_BYTES_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getBillableIngestedBytesAggSum_JsonNullable() {
    return billableIngestedBytesAggSum;
  }

  @JsonProperty(JSON_PROPERTY_BILLABLE_INGESTED_BYTES_AGG_SUM)
  public void setBillableIngestedBytesAggSum_JsonNullable(
      JsonNullable<Long> billableIngestedBytesAggSum) {
    this.billableIngestedBytesAggSum = billableIngestedBytesAggSum;
  }

  public void setBillableIngestedBytesAggSum(Long billableIngestedBytesAggSum) {
    this.billableIngestedBytesAggSum = JsonNullable.<Long>of(billableIngestedBytesAggSum);
  }

  public UsageSummaryResponse complianceContainerAggSum(Long complianceContainerAggSum) {
    this.complianceContainerAggSum = JsonNullable.<Long>of(complianceContainerAggSum);
    return this;
  }

  /**
   * Shows the sum of all compliance containers over all hours in the current months for all
   * organizations.
   *
   * @return complianceContainerAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all compliance containers over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getComplianceContainerAggSum() {
    return complianceContainerAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMPLIANCE_CONTAINER_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getComplianceContainerAggSum_JsonNullable() {
    return complianceContainerAggSum;
  }

  @JsonProperty(JSON_PROPERTY_COMPLIANCE_CONTAINER_AGG_SUM)
  public void setComplianceContainerAggSum_JsonNullable(
      JsonNullable<Long> complianceContainerAggSum) {
    this.complianceContainerAggSum = complianceContainerAggSum;
  }

  public void setComplianceContainerAggSum(Long complianceContainerAggSum) {
    this.complianceContainerAggSum = JsonNullable.<Long>of(complianceContainerAggSum);
  }

  public UsageSummaryResponse complianceHostAggSum(Long complianceHostAggSum) {
    this.complianceHostAggSum = JsonNullable.<Long>of(complianceHostAggSum);
    return this;
  }

  /**
   * Shows the sum of all compliance hosts over all hours in the current months for all
   * organizations.
   *
   * @return complianceHostAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all compliance hosts over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getComplianceHostAggSum() {
    return complianceHostAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMPLIANCE_HOST_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getComplianceHostAggSum_JsonNullable() {
    return complianceHostAggSum;
  }

  @JsonProperty(JSON_PROPERTY_COMPLIANCE_HOST_AGG_SUM)
  public void setComplianceHostAggSum_JsonNullable(JsonNullable<Long> complianceHostAggSum) {
    this.complianceHostAggSum = complianceHostAggSum;
  }

  public void setComplianceHostAggSum(Long complianceHostAggSum) {
    this.complianceHostAggSum = JsonNullable.<Long>of(complianceHostAggSum);
  }

  public UsageSummaryResponse containerAvgSum(Long containerAvgSum) {
    this.containerAvgSum = JsonNullable.<Long>of(containerAvgSum);
    return this;
  }

  /**
   * Shows the average of all distinct containers over all hours in the current months for all
   * organizations.
   *
   * @return containerAvgSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the average of all distinct containers over all hours in the current months for"
              + " all organizations.")
  @JsonIgnore
  public Long getContainerAvgSum() {
    return containerAvgSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONTAINER_AVG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getContainerAvgSum_JsonNullable() {
    return containerAvgSum;
  }

  @JsonProperty(JSON_PROPERTY_CONTAINER_AVG_SUM)
  public void setContainerAvgSum_JsonNullable(JsonNullable<Long> containerAvgSum) {
    this.containerAvgSum = containerAvgSum;
  }

  public void setContainerAvgSum(Long containerAvgSum) {
    this.containerAvgSum = JsonNullable.<Long>of(containerAvgSum);
  }

  public UsageSummaryResponse containerHwmSum(Long containerHwmSum) {
    this.containerHwmSum = JsonNullable.<Long>of(containerHwmSum);
    return this;
  }

  /**
   * Shows the sum of the high-water marks of all distinct containers over all hours in the current
   * months for all organizations.
   *
   * @return containerHwmSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of the high-water marks of all distinct containers over all hours in the"
              + " current months for all organizations.")
  @JsonIgnore
  public Long getContainerHwmSum() {
    return containerHwmSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONTAINER_HWM_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getContainerHwmSum_JsonNullable() {
    return containerHwmSum;
  }

  @JsonProperty(JSON_PROPERTY_CONTAINER_HWM_SUM)
  public void setContainerHwmSum_JsonNullable(JsonNullable<Long> containerHwmSum) {
    this.containerHwmSum = containerHwmSum;
  }

  public void setContainerHwmSum(Long containerHwmSum) {
    this.containerHwmSum = JsonNullable.<Long>of(containerHwmSum);
  }

  public UsageSummaryResponse customTsSum(Long customTsSum) {
    this.customTsSum = JsonNullable.<Long>of(customTsSum);
    return this;
  }

  /**
   * Shows the average number of distinct custom metrics over all hours in the current months for
   * all organizations.
   *
   * @return customTsSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the average number of distinct custom metrics over all hours in the current"
              + " months for all organizations.")
  @JsonIgnore
  public Long getCustomTsSum() {
    return customTsSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CUSTOM_TS_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getCustomTsSum_JsonNullable() {
    return customTsSum;
  }

  @JsonProperty(JSON_PROPERTY_CUSTOM_TS_SUM)
  public void setCustomTsSum_JsonNullable(JsonNullable<Long> customTsSum) {
    this.customTsSum = customTsSum;
  }

  public void setCustomTsSum(Long customTsSum) {
    this.customTsSum = JsonNullable.<Long>of(customTsSum);
  }

  public UsageSummaryResponse endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * Shows the last date of usage in the current months for all organizations.
   *
   * @return endDate
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value = "Shows the last date of usage in the current months for all organizations.")
  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public UsageSummaryResponse fargateTasksCountAvgSum(Long fargateTasksCountAvgSum) {
    this.fargateTasksCountAvgSum = JsonNullable.<Long>of(fargateTasksCountAvgSum);
    return this;
  }

  /**
   * Shows the average of all Fargate tasks over all hours in the current months for all
   * organizations.
   *
   * @return fargateTasksCountAvgSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the average of all Fargate tasks over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getFargateTasksCountAvgSum() {
    return fargateTasksCountAvgSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FARGATE_TASKS_COUNT_AVG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getFargateTasksCountAvgSum_JsonNullable() {
    return fargateTasksCountAvgSum;
  }

  @JsonProperty(JSON_PROPERTY_FARGATE_TASKS_COUNT_AVG_SUM)
  public void setFargateTasksCountAvgSum_JsonNullable(JsonNullable<Long> fargateTasksCountAvgSum) {
    this.fargateTasksCountAvgSum = fargateTasksCountAvgSum;
  }

  public void setFargateTasksCountAvgSum(Long fargateTasksCountAvgSum) {
    this.fargateTasksCountAvgSum = JsonNullable.<Long>of(fargateTasksCountAvgSum);
  }

  public UsageSummaryResponse fargateTasksCountHwmSum(Long fargateTasksCountHwmSum) {
    this.fargateTasksCountHwmSum = JsonNullable.<Long>of(fargateTasksCountHwmSum);
    return this;
  }

  /**
   * Shows the sum of the high-water marks of all Fargate tasks over all hours in the current months
   * for all organizations.
   *
   * @return fargateTasksCountHwmSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of the high-water marks of all Fargate tasks over all hours in the"
              + " current months for all organizations.")
  @JsonIgnore
  public Long getFargateTasksCountHwmSum() {
    return fargateTasksCountHwmSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FARGATE_TASKS_COUNT_HWM_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getFargateTasksCountHwmSum_JsonNullable() {
    return fargateTasksCountHwmSum;
  }

  @JsonProperty(JSON_PROPERTY_FARGATE_TASKS_COUNT_HWM_SUM)
  public void setFargateTasksCountHwmSum_JsonNullable(JsonNullable<Long> fargateTasksCountHwmSum) {
    this.fargateTasksCountHwmSum = fargateTasksCountHwmSum;
  }

  public void setFargateTasksCountHwmSum(Long fargateTasksCountHwmSum) {
    this.fargateTasksCountHwmSum = JsonNullable.<Long>of(fargateTasksCountHwmSum);
  }

  public UsageSummaryResponse gcpHostTop99pSum(Long gcpHostTop99pSum) {
    this.gcpHostTop99pSum = JsonNullable.<Long>of(gcpHostTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all GCP hosts over all hours in the current months for all
   * organizations.
   *
   * @return gcpHostTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all GCP hosts over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getGcpHostTop99pSum() {
    return gcpHostTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_GCP_HOST_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getGcpHostTop99pSum_JsonNullable() {
    return gcpHostTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_GCP_HOST_TOP99P_SUM)
  public void setGcpHostTop99pSum_JsonNullable(JsonNullable<Long> gcpHostTop99pSum) {
    this.gcpHostTop99pSum = gcpHostTop99pSum;
  }

  public void setGcpHostTop99pSum(Long gcpHostTop99pSum) {
    this.gcpHostTop99pSum = JsonNullable.<Long>of(gcpHostTop99pSum);
  }

  public UsageSummaryResponse herokuHostTop99pSum(Long herokuHostTop99pSum) {
    this.herokuHostTop99pSum = JsonNullable.<Long>of(herokuHostTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all Heroku dynos over all hours in the current months for all
   * organizations.
   *
   * @return herokuHostTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all Heroku dynos over all hours in the current months for"
              + " all organizations.")
  @JsonIgnore
  public Long getHerokuHostTop99pSum() {
    return herokuHostTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_HEROKU_HOST_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getHerokuHostTop99pSum_JsonNullable() {
    return herokuHostTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_HEROKU_HOST_TOP99P_SUM)
  public void setHerokuHostTop99pSum_JsonNullable(JsonNullable<Long> herokuHostTop99pSum) {
    this.herokuHostTop99pSum = herokuHostTop99pSum;
  }

  public void setHerokuHostTop99pSum(Long herokuHostTop99pSum) {
    this.herokuHostTop99pSum = JsonNullable.<Long>of(herokuHostTop99pSum);
  }

  public UsageSummaryResponse incidentManagementMonthlyActiveUsersHwmSum(
      Long incidentManagementMonthlyActiveUsersHwmSum) {
    this.incidentManagementMonthlyActiveUsersHwmSum =
        JsonNullable.<Long>of(incidentManagementMonthlyActiveUsersHwmSum);
    return this;
  }

  /**
   * Shows sum of the the high-water marks of incident management monthly active users in the
   * current months for all organizations.
   *
   * @return incidentManagementMonthlyActiveUsersHwmSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows sum of the the high-water marks of incident management monthly active users in"
              + " the current months for all organizations.")
  @JsonIgnore
  public Long getIncidentManagementMonthlyActiveUsersHwmSum() {
    return incidentManagementMonthlyActiveUsersHwmSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INCIDENT_MANAGEMENT_MONTHLY_ACTIVE_USERS_HWM_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getIncidentManagementMonthlyActiveUsersHwmSum_JsonNullable() {
    return incidentManagementMonthlyActiveUsersHwmSum;
  }

  @JsonProperty(JSON_PROPERTY_INCIDENT_MANAGEMENT_MONTHLY_ACTIVE_USERS_HWM_SUM)
  public void setIncidentManagementMonthlyActiveUsersHwmSum_JsonNullable(
      JsonNullable<Long> incidentManagementMonthlyActiveUsersHwmSum) {
    this.incidentManagementMonthlyActiveUsersHwmSum = incidentManagementMonthlyActiveUsersHwmSum;
  }

  public void setIncidentManagementMonthlyActiveUsersHwmSum(
      Long incidentManagementMonthlyActiveUsersHwmSum) {
    this.incidentManagementMonthlyActiveUsersHwmSum =
        JsonNullable.<Long>of(incidentManagementMonthlyActiveUsersHwmSum);
  }

  public UsageSummaryResponse indexedEventsCountAggSum(Long indexedEventsCountAggSum) {
    this.indexedEventsCountAggSum = JsonNullable.<Long>of(indexedEventsCountAggSum);
    return this;
  }

  /**
   * Shows the sum of all log events indexed over all hours in the current months for all
   * organizations.
   *
   * @return indexedEventsCountAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all log events indexed over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getIndexedEventsCountAggSum() {
    return indexedEventsCountAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INDEXED_EVENTS_COUNT_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getIndexedEventsCountAggSum_JsonNullable() {
    return indexedEventsCountAggSum;
  }

  @JsonProperty(JSON_PROPERTY_INDEXED_EVENTS_COUNT_AGG_SUM)
  public void setIndexedEventsCountAggSum_JsonNullable(
      JsonNullable<Long> indexedEventsCountAggSum) {
    this.indexedEventsCountAggSum = indexedEventsCountAggSum;
  }

  public void setIndexedEventsCountAggSum(Long indexedEventsCountAggSum) {
    this.indexedEventsCountAggSum = JsonNullable.<Long>of(indexedEventsCountAggSum);
  }

  public UsageSummaryResponse infraHostTop99pSum(Long infraHostTop99pSum) {
    this.infraHostTop99pSum = JsonNullable.<Long>of(infraHostTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all distinct infrastructure hosts over all hours in the current
   * months for all organizations.
   *
   * @return infraHostTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all distinct infrastructure hosts over all hours in the"
              + " current months for all organizations.")
  @JsonIgnore
  public Long getInfraHostTop99pSum() {
    return infraHostTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INFRA_HOST_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getInfraHostTop99pSum_JsonNullable() {
    return infraHostTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_INFRA_HOST_TOP99P_SUM)
  public void setInfraHostTop99pSum_JsonNullable(JsonNullable<Long> infraHostTop99pSum) {
    this.infraHostTop99pSum = infraHostTop99pSum;
  }

  public void setInfraHostTop99pSum(Long infraHostTop99pSum) {
    this.infraHostTop99pSum = JsonNullable.<Long>of(infraHostTop99pSum);
  }

  public UsageSummaryResponse ingestedEventsBytesAggSum(Long ingestedEventsBytesAggSum) {
    this.ingestedEventsBytesAggSum = JsonNullable.<Long>of(ingestedEventsBytesAggSum);
    return this;
  }

  /**
   * Shows the sum of all log bytes ingested over all hours in the current months for all
   * organizations.
   *
   * @return ingestedEventsBytesAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all log bytes ingested over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getIngestedEventsBytesAggSum() {
    return ingestedEventsBytesAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INGESTED_EVENTS_BYTES_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getIngestedEventsBytesAggSum_JsonNullable() {
    return ingestedEventsBytesAggSum;
  }

  @JsonProperty(JSON_PROPERTY_INGESTED_EVENTS_BYTES_AGG_SUM)
  public void setIngestedEventsBytesAggSum_JsonNullable(
      JsonNullable<Long> ingestedEventsBytesAggSum) {
    this.ingestedEventsBytesAggSum = ingestedEventsBytesAggSum;
  }

  public void setIngestedEventsBytesAggSum(Long ingestedEventsBytesAggSum) {
    this.ingestedEventsBytesAggSum = JsonNullable.<Long>of(ingestedEventsBytesAggSum);
  }

  public UsageSummaryResponse iotDeviceAggSum(Long iotDeviceAggSum) {
    this.iotDeviceAggSum = JsonNullable.<Long>of(iotDeviceAggSum);
    return this;
  }

  /**
   * Shows the sum of all IoT devices over all hours in the current months for all organizations.
   *
   * @return iotDeviceAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all IoT devices over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getIotDeviceAggSum() {
    return iotDeviceAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IOT_DEVICE_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getIotDeviceAggSum_JsonNullable() {
    return iotDeviceAggSum;
  }

  @JsonProperty(JSON_PROPERTY_IOT_DEVICE_AGG_SUM)
  public void setIotDeviceAggSum_JsonNullable(JsonNullable<Long> iotDeviceAggSum) {
    this.iotDeviceAggSum = iotDeviceAggSum;
  }

  public void setIotDeviceAggSum(Long iotDeviceAggSum) {
    this.iotDeviceAggSum = JsonNullable.<Long>of(iotDeviceAggSum);
  }

  public UsageSummaryResponse iotDeviceTop99pSum(Long iotDeviceTop99pSum) {
    this.iotDeviceTop99pSum = JsonNullable.<Long>of(iotDeviceTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all IoT devices over all hours in the current months of all
   * organizations.
   *
   * @return iotDeviceTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all IoT devices over all hours in the current months of"
              + " all organizations.")
  @JsonIgnore
  public Long getIotDeviceTop99pSum() {
    return iotDeviceTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IOT_DEVICE_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getIotDeviceTop99pSum_JsonNullable() {
    return iotDeviceTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_IOT_DEVICE_TOP99P_SUM)
  public void setIotDeviceTop99pSum_JsonNullable(JsonNullable<Long> iotDeviceTop99pSum) {
    this.iotDeviceTop99pSum = iotDeviceTop99pSum;
  }

  public void setIotDeviceTop99pSum(Long iotDeviceTop99pSum) {
    this.iotDeviceTop99pSum = JsonNullable.<Long>of(iotDeviceTop99pSum);
  }

  public UsageSummaryResponse lastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

  /**
   * Shows the the most recent hour in the current months for all organizations for which all usages
   * were calculated.
   *
   * @return lastUpdated
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the the most recent hour in the current months for all organizations for which"
              + " all usages were calculated.")
  @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }

  public void setLastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }

  public UsageSummaryResponse liveIndexedEventsAggSum(Long liveIndexedEventsAggSum) {
    this.liveIndexedEventsAggSum = JsonNullable.<Long>of(liveIndexedEventsAggSum);
    return this;
  }

  /**
   * Shows the sum of all live logs indexed over all hours in the current months for all
   * organizations (data available as of December 1, 2020).
   *
   * @return liveIndexedEventsAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all live logs indexed over all hours in the current months for all"
              + " organizations (data available as of December 1, 2020).")
  @JsonIgnore
  public Long getLiveIndexedEventsAggSum() {
    return liveIndexedEventsAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LIVE_INDEXED_EVENTS_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getLiveIndexedEventsAggSum_JsonNullable() {
    return liveIndexedEventsAggSum;
  }

  @JsonProperty(JSON_PROPERTY_LIVE_INDEXED_EVENTS_AGG_SUM)
  public void setLiveIndexedEventsAggSum_JsonNullable(JsonNullable<Long> liveIndexedEventsAggSum) {
    this.liveIndexedEventsAggSum = liveIndexedEventsAggSum;
  }

  public void setLiveIndexedEventsAggSum(Long liveIndexedEventsAggSum) {
    this.liveIndexedEventsAggSum = JsonNullable.<Long>of(liveIndexedEventsAggSum);
  }

  public UsageSummaryResponse liveIngestedBytesAggSum(Long liveIngestedBytesAggSum) {
    this.liveIngestedBytesAggSum = JsonNullable.<Long>of(liveIngestedBytesAggSum);
    return this;
  }

  /**
   * Shows the sum of all live logs bytes ingested over all hours in the current months for all
   * organizations (data available as of December 1, 2020).
   *
   * @return liveIngestedBytesAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all live logs bytes ingested over all hours in the current months for"
              + " all organizations (data available as of December 1, 2020).")
  @JsonIgnore
  public Long getLiveIngestedBytesAggSum() {
    return liveIngestedBytesAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LIVE_INGESTED_BYTES_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getLiveIngestedBytesAggSum_JsonNullable() {
    return liveIngestedBytesAggSum;
  }

  @JsonProperty(JSON_PROPERTY_LIVE_INGESTED_BYTES_AGG_SUM)
  public void setLiveIngestedBytesAggSum_JsonNullable(JsonNullable<Long> liveIngestedBytesAggSum) {
    this.liveIngestedBytesAggSum = liveIngestedBytesAggSum;
  }

  public void setLiveIngestedBytesAggSum(Long liveIngestedBytesAggSum) {
    this.liveIngestedBytesAggSum = JsonNullable.<Long>of(liveIngestedBytesAggSum);
  }

  public UsageSummaryResponse mobileRumSessionCountAggSum(Long mobileRumSessionCountAggSum) {
    this.mobileRumSessionCountAggSum = JsonNullable.<Long>of(mobileRumSessionCountAggSum);
    return this;
  }

  /**
   * Shows the sum of all mobile RUM Sessions over all hours in the current months for all
   * organizations.
   *
   * @return mobileRumSessionCountAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all mobile RUM Sessions over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getMobileRumSessionCountAggSum() {
    return mobileRumSessionCountAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getMobileRumSessionCountAggSum_JsonNullable() {
    return mobileRumSessionCountAggSum;
  }

  @JsonProperty(JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_AGG_SUM)
  public void setMobileRumSessionCountAggSum_JsonNullable(
      JsonNullable<Long> mobileRumSessionCountAggSum) {
    this.mobileRumSessionCountAggSum = mobileRumSessionCountAggSum;
  }

  public void setMobileRumSessionCountAggSum(Long mobileRumSessionCountAggSum) {
    this.mobileRumSessionCountAggSum = JsonNullable.<Long>of(mobileRumSessionCountAggSum);
  }

  public UsageSummaryResponse mobileRumSessionCountAndroidAggSum(
      Long mobileRumSessionCountAndroidAggSum) {
    this.mobileRumSessionCountAndroidAggSum =
        JsonNullable.<Long>of(mobileRumSessionCountAndroidAggSum);
    return this;
  }

  /**
   * Shows the sum of all mobile RUM Sessions on Android over all hours in the current months for
   * all organizations.
   *
   * @return mobileRumSessionCountAndroidAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all mobile RUM Sessions on Android over all hours in the current"
              + " months for all organizations.")
  @JsonIgnore
  public Long getMobileRumSessionCountAndroidAggSum() {
    return mobileRumSessionCountAndroidAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_ANDROID_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getMobileRumSessionCountAndroidAggSum_JsonNullable() {
    return mobileRumSessionCountAndroidAggSum;
  }

  @JsonProperty(JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_ANDROID_AGG_SUM)
  public void setMobileRumSessionCountAndroidAggSum_JsonNullable(
      JsonNullable<Long> mobileRumSessionCountAndroidAggSum) {
    this.mobileRumSessionCountAndroidAggSum = mobileRumSessionCountAndroidAggSum;
  }

  public void setMobileRumSessionCountAndroidAggSum(Long mobileRumSessionCountAndroidAggSum) {
    this.mobileRumSessionCountAndroidAggSum =
        JsonNullable.<Long>of(mobileRumSessionCountAndroidAggSum);
  }

  public UsageSummaryResponse mobileRumSessionCountIosAggSum(Long mobileRumSessionCountIosAggSum) {
    this.mobileRumSessionCountIosAggSum = JsonNullable.<Long>of(mobileRumSessionCountIosAggSum);
    return this;
  }

  /**
   * Shows the sum of all mobile RUM Sessions on iOS over all hours in the current months for all
   * organizations.
   *
   * @return mobileRumSessionCountIosAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all mobile RUM Sessions on iOS over all hours in the current months"
              + " for all organizations.")
  @JsonIgnore
  public Long getMobileRumSessionCountIosAggSum() {
    return mobileRumSessionCountIosAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_IOS_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getMobileRumSessionCountIosAggSum_JsonNullable() {
    return mobileRumSessionCountIosAggSum;
  }

  @JsonProperty(JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_IOS_AGG_SUM)
  public void setMobileRumSessionCountIosAggSum_JsonNullable(
      JsonNullable<Long> mobileRumSessionCountIosAggSum) {
    this.mobileRumSessionCountIosAggSum = mobileRumSessionCountIosAggSum;
  }

  public void setMobileRumSessionCountIosAggSum(Long mobileRumSessionCountIosAggSum) {
    this.mobileRumSessionCountIosAggSum = JsonNullable.<Long>of(mobileRumSessionCountIosAggSum);
  }

  public UsageSummaryResponse netflowIndexedEventsCountAggSum(
      Long netflowIndexedEventsCountAggSum) {
    this.netflowIndexedEventsCountAggSum = JsonNullable.<Long>of(netflowIndexedEventsCountAggSum);
    return this;
  }

  /**
   * Shows the sum of all Network flows indexed over all hours in the current months for all
   * organizations.
   *
   * @return netflowIndexedEventsCountAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all Network flows indexed over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getNetflowIndexedEventsCountAggSum() {
    return netflowIndexedEventsCountAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NETFLOW_INDEXED_EVENTS_COUNT_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getNetflowIndexedEventsCountAggSum_JsonNullable() {
    return netflowIndexedEventsCountAggSum;
  }

  @JsonProperty(JSON_PROPERTY_NETFLOW_INDEXED_EVENTS_COUNT_AGG_SUM)
  public void setNetflowIndexedEventsCountAggSum_JsonNullable(
      JsonNullable<Long> netflowIndexedEventsCountAggSum) {
    this.netflowIndexedEventsCountAggSum = netflowIndexedEventsCountAggSum;
  }

  public void setNetflowIndexedEventsCountAggSum(Long netflowIndexedEventsCountAggSum) {
    this.netflowIndexedEventsCountAggSum = JsonNullable.<Long>of(netflowIndexedEventsCountAggSum);
  }

  public UsageSummaryResponse npmHostTop99pSum(Long npmHostTop99pSum) {
    this.npmHostTop99pSum = JsonNullable.<Long>of(npmHostTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all distinct Networks hosts over all hours in the current months
   * for all organizations.
   *
   * @return npmHostTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all distinct Networks hosts over all hours in the current"
              + " months for all organizations.")
  @JsonIgnore
  public Long getNpmHostTop99pSum() {
    return npmHostTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NPM_HOST_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getNpmHostTop99pSum_JsonNullable() {
    return npmHostTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_NPM_HOST_TOP99P_SUM)
  public void setNpmHostTop99pSum_JsonNullable(JsonNullable<Long> npmHostTop99pSum) {
    this.npmHostTop99pSum = npmHostTop99pSum;
  }

  public void setNpmHostTop99pSum(Long npmHostTop99pSum) {
    this.npmHostTop99pSum = JsonNullable.<Long>of(npmHostTop99pSum);
  }

  public UsageSummaryResponse opentelemetryHostTop99pSum(Long opentelemetryHostTop99pSum) {
    this.opentelemetryHostTop99pSum = JsonNullable.<Long>of(opentelemetryHostTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all hosts reported by the Datadog exporter for the OpenTelemetry
   * Collector over all hours in the current months for all organizations.
   *
   * @return opentelemetryHostTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all hosts reported by the Datadog exporter for the"
              + " OpenTelemetry Collector over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getOpentelemetryHostTop99pSum() {
    return opentelemetryHostTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OPENTELEMETRY_HOST_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getOpentelemetryHostTop99pSum_JsonNullable() {
    return opentelemetryHostTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_OPENTELEMETRY_HOST_TOP99P_SUM)
  public void setOpentelemetryHostTop99pSum_JsonNullable(
      JsonNullable<Long> opentelemetryHostTop99pSum) {
    this.opentelemetryHostTop99pSum = opentelemetryHostTop99pSum;
  }

  public void setOpentelemetryHostTop99pSum(Long opentelemetryHostTop99pSum) {
    this.opentelemetryHostTop99pSum = JsonNullable.<Long>of(opentelemetryHostTop99pSum);
  }

  public UsageSummaryResponse profilingContainerAgentCountAvg(
      Long profilingContainerAgentCountAvg) {
    this.profilingContainerAgentCountAvg = JsonNullable.<Long>of(profilingContainerAgentCountAvg);
    return this;
  }

  /**
   * Shows the average number of profiled containers over all hours in the current months for all
   * organizations.
   *
   * @return profilingContainerAgentCountAvg
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the average number of profiled containers over all hours in the current months"
              + " for all organizations.")
  @JsonIgnore
  public Long getProfilingContainerAgentCountAvg() {
    return profilingContainerAgentCountAvg.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROFILING_CONTAINER_AGENT_COUNT_AVG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getProfilingContainerAgentCountAvg_JsonNullable() {
    return profilingContainerAgentCountAvg;
  }

  @JsonProperty(JSON_PROPERTY_PROFILING_CONTAINER_AGENT_COUNT_AVG)
  public void setProfilingContainerAgentCountAvg_JsonNullable(
      JsonNullable<Long> profilingContainerAgentCountAvg) {
    this.profilingContainerAgentCountAvg = profilingContainerAgentCountAvg;
  }

  public void setProfilingContainerAgentCountAvg(Long profilingContainerAgentCountAvg) {
    this.profilingContainerAgentCountAvg = JsonNullable.<Long>of(profilingContainerAgentCountAvg);
  }

  public UsageSummaryResponse profilingHostCountTop99pSum(Long profilingHostCountTop99pSum) {
    this.profilingHostCountTop99pSum = JsonNullable.<Long>of(profilingHostCountTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all profiled hosts over all hours in the current months for all
   * organizations.
   *
   * @return profilingHostCountTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all profiled hosts over all hours in the current months"
              + " for all organizations.")
  @JsonIgnore
  public Long getProfilingHostCountTop99pSum() {
    return profilingHostCountTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROFILING_HOST_COUNT_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getProfilingHostCountTop99pSum_JsonNullable() {
    return profilingHostCountTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_PROFILING_HOST_COUNT_TOP99P_SUM)
  public void setProfilingHostCountTop99pSum_JsonNullable(
      JsonNullable<Long> profilingHostCountTop99pSum) {
    this.profilingHostCountTop99pSum = profilingHostCountTop99pSum;
  }

  public void setProfilingHostCountTop99pSum(Long profilingHostCountTop99pSum) {
    this.profilingHostCountTop99pSum = JsonNullable.<Long>of(profilingHostCountTop99pSum);
  }

  public UsageSummaryResponse rehydratedIndexedEventsAggSum(Long rehydratedIndexedEventsAggSum) {
    this.rehydratedIndexedEventsAggSum = JsonNullable.<Long>of(rehydratedIndexedEventsAggSum);
    return this;
  }

  /**
   * Shows the sum of all rehydrated logs indexed over all hours in the current months for all
   * organizations (data available as of December 1, 2020).
   *
   * @return rehydratedIndexedEventsAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all rehydrated logs indexed over all hours in the current months for"
              + " all organizations (data available as of December 1, 2020).")
  @JsonIgnore
  public Long getRehydratedIndexedEventsAggSum() {
    return rehydratedIndexedEventsAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_REHYDRATED_INDEXED_EVENTS_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getRehydratedIndexedEventsAggSum_JsonNullable() {
    return rehydratedIndexedEventsAggSum;
  }

  @JsonProperty(JSON_PROPERTY_REHYDRATED_INDEXED_EVENTS_AGG_SUM)
  public void setRehydratedIndexedEventsAggSum_JsonNullable(
      JsonNullable<Long> rehydratedIndexedEventsAggSum) {
    this.rehydratedIndexedEventsAggSum = rehydratedIndexedEventsAggSum;
  }

  public void setRehydratedIndexedEventsAggSum(Long rehydratedIndexedEventsAggSum) {
    this.rehydratedIndexedEventsAggSum = JsonNullable.<Long>of(rehydratedIndexedEventsAggSum);
  }

  public UsageSummaryResponse rehydratedIngestedBytesAggSum(Long rehydratedIngestedBytesAggSum) {
    this.rehydratedIngestedBytesAggSum = JsonNullable.<Long>of(rehydratedIngestedBytesAggSum);
    return this;
  }

  /**
   * Shows the sum of all rehydrated logs bytes ingested over all hours in the current months for
   * all organizations (data available as of December 1, 2020).
   *
   * @return rehydratedIngestedBytesAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all rehydrated logs bytes ingested over all hours in the current"
              + " months for all organizations (data available as of December 1, 2020).")
  @JsonIgnore
  public Long getRehydratedIngestedBytesAggSum() {
    return rehydratedIngestedBytesAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_REHYDRATED_INGESTED_BYTES_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getRehydratedIngestedBytesAggSum_JsonNullable() {
    return rehydratedIngestedBytesAggSum;
  }

  @JsonProperty(JSON_PROPERTY_REHYDRATED_INGESTED_BYTES_AGG_SUM)
  public void setRehydratedIngestedBytesAggSum_JsonNullable(
      JsonNullable<Long> rehydratedIngestedBytesAggSum) {
    this.rehydratedIngestedBytesAggSum = rehydratedIngestedBytesAggSum;
  }

  public void setRehydratedIngestedBytesAggSum(Long rehydratedIngestedBytesAggSum) {
    this.rehydratedIngestedBytesAggSum = JsonNullable.<Long>of(rehydratedIngestedBytesAggSum);
  }

  public UsageSummaryResponse rumSessionCountAggSum(Long rumSessionCountAggSum) {
    this.rumSessionCountAggSum = JsonNullable.<Long>of(rumSessionCountAggSum);
    return this;
  }

  /**
   * Shows the sum of all browser RUM Sessions over all hours in the current months for all
   * organizations.
   *
   * @return rumSessionCountAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all browser RUM Sessions over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getRumSessionCountAggSum() {
    return rumSessionCountAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RUM_SESSION_COUNT_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getRumSessionCountAggSum_JsonNullable() {
    return rumSessionCountAggSum;
  }

  @JsonProperty(JSON_PROPERTY_RUM_SESSION_COUNT_AGG_SUM)
  public void setRumSessionCountAggSum_JsonNullable(JsonNullable<Long> rumSessionCountAggSum) {
    this.rumSessionCountAggSum = rumSessionCountAggSum;
  }

  public void setRumSessionCountAggSum(Long rumSessionCountAggSum) {
    this.rumSessionCountAggSum = JsonNullable.<Long>of(rumSessionCountAggSum);
  }

  public UsageSummaryResponse rumTotalSessionCountAggSum(Long rumTotalSessionCountAggSum) {
    this.rumTotalSessionCountAggSum = JsonNullable.<Long>of(rumTotalSessionCountAggSum);
    return this;
  }

  /**
   * Shows the sum of RUM Sessions (browser and mobile) over all hours in the current months for all
   * organizations.
   *
   * @return rumTotalSessionCountAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of RUM Sessions (browser and mobile) over all hours in the current months"
              + " for all organizations.")
  @JsonIgnore
  public Long getRumTotalSessionCountAggSum() {
    return rumTotalSessionCountAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RUM_TOTAL_SESSION_COUNT_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getRumTotalSessionCountAggSum_JsonNullable() {
    return rumTotalSessionCountAggSum;
  }

  @JsonProperty(JSON_PROPERTY_RUM_TOTAL_SESSION_COUNT_AGG_SUM)
  public void setRumTotalSessionCountAggSum_JsonNullable(
      JsonNullable<Long> rumTotalSessionCountAggSum) {
    this.rumTotalSessionCountAggSum = rumTotalSessionCountAggSum;
  }

  public void setRumTotalSessionCountAggSum(Long rumTotalSessionCountAggSum) {
    this.rumTotalSessionCountAggSum = JsonNullable.<Long>of(rumTotalSessionCountAggSum);
  }

  public UsageSummaryResponse startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * Shows the first date of usage in the current months for all organizations.
   *
   * @return startDate
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value = "Shows the first date of usage in the current months for all organizations.")
  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public UsageSummaryResponse syntheticsBrowserCheckCallsCountAggSum(
      Long syntheticsBrowserCheckCallsCountAggSum) {
    this.syntheticsBrowserCheckCallsCountAggSum =
        JsonNullable.<Long>of(syntheticsBrowserCheckCallsCountAggSum);
    return this;
  }

  /**
   * Shows the sum of all Synthetic browser tests over all hours in the current months for all
   * organizations.
   *
   * @return syntheticsBrowserCheckCallsCountAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all Synthetic browser tests over all hours in the current months for"
              + " all organizations.")
  @JsonIgnore
  public Long getSyntheticsBrowserCheckCallsCountAggSum() {
    return syntheticsBrowserCheckCallsCountAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SYNTHETICS_BROWSER_CHECK_CALLS_COUNT_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getSyntheticsBrowserCheckCallsCountAggSum_JsonNullable() {
    return syntheticsBrowserCheckCallsCountAggSum;
  }

  @JsonProperty(JSON_PROPERTY_SYNTHETICS_BROWSER_CHECK_CALLS_COUNT_AGG_SUM)
  public void setSyntheticsBrowserCheckCallsCountAggSum_JsonNullable(
      JsonNullable<Long> syntheticsBrowserCheckCallsCountAggSum) {
    this.syntheticsBrowserCheckCallsCountAggSum = syntheticsBrowserCheckCallsCountAggSum;
  }

  public void setSyntheticsBrowserCheckCallsCountAggSum(
      Long syntheticsBrowserCheckCallsCountAggSum) {
    this.syntheticsBrowserCheckCallsCountAggSum =
        JsonNullable.<Long>of(syntheticsBrowserCheckCallsCountAggSum);
  }

  public UsageSummaryResponse syntheticsCheckCallsCountAggSum(
      Long syntheticsCheckCallsCountAggSum) {
    this.syntheticsCheckCallsCountAggSum = JsonNullable.<Long>of(syntheticsCheckCallsCountAggSum);
    return this;
  }

  /**
   * Shows the sum of all Synthetic API tests over all hours in the current months for all
   * organizations.
   *
   * @return syntheticsCheckCallsCountAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all Synthetic API tests over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getSyntheticsCheckCallsCountAggSum() {
    return syntheticsCheckCallsCountAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SYNTHETICS_CHECK_CALLS_COUNT_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getSyntheticsCheckCallsCountAggSum_JsonNullable() {
    return syntheticsCheckCallsCountAggSum;
  }

  @JsonProperty(JSON_PROPERTY_SYNTHETICS_CHECK_CALLS_COUNT_AGG_SUM)
  public void setSyntheticsCheckCallsCountAggSum_JsonNullable(
      JsonNullable<Long> syntheticsCheckCallsCountAggSum) {
    this.syntheticsCheckCallsCountAggSum = syntheticsCheckCallsCountAggSum;
  }

  public void setSyntheticsCheckCallsCountAggSum(Long syntheticsCheckCallsCountAggSum) {
    this.syntheticsCheckCallsCountAggSum = JsonNullable.<Long>of(syntheticsCheckCallsCountAggSum);
  }

  public UsageSummaryResponse traceSearchIndexedEventsCountAggSum(
      Long traceSearchIndexedEventsCountAggSum) {
    this.traceSearchIndexedEventsCountAggSum =
        JsonNullable.<Long>of(traceSearchIndexedEventsCountAggSum);
    return this;
  }

  /**
   * Shows the sum of all Indexed Spans indexed over all hours in the current months for all
   * organizations.
   *
   * @return traceSearchIndexedEventsCountAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all Indexed Spans indexed over all hours in the current months for all"
              + " organizations.")
  @JsonIgnore
  public Long getTraceSearchIndexedEventsCountAggSum() {
    return traceSearchIndexedEventsCountAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TRACE_SEARCH_INDEXED_EVENTS_COUNT_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getTraceSearchIndexedEventsCountAggSum_JsonNullable() {
    return traceSearchIndexedEventsCountAggSum;
  }

  @JsonProperty(JSON_PROPERTY_TRACE_SEARCH_INDEXED_EVENTS_COUNT_AGG_SUM)
  public void setTraceSearchIndexedEventsCountAggSum_JsonNullable(
      JsonNullable<Long> traceSearchIndexedEventsCountAggSum) {
    this.traceSearchIndexedEventsCountAggSum = traceSearchIndexedEventsCountAggSum;
  }

  public void setTraceSearchIndexedEventsCountAggSum(Long traceSearchIndexedEventsCountAggSum) {
    this.traceSearchIndexedEventsCountAggSum =
        JsonNullable.<Long>of(traceSearchIndexedEventsCountAggSum);
  }

  public UsageSummaryResponse twolIngestedEventsBytesAggSum(Long twolIngestedEventsBytesAggSum) {
    this.twolIngestedEventsBytesAggSum = JsonNullable.<Long>of(twolIngestedEventsBytesAggSum);
    return this;
  }

  /**
   * Shows the sum of all tracing without limits bytes ingested over all hours in the current months
   * for all organizations.
   *
   * @return twolIngestedEventsBytesAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all tracing without limits bytes ingested over all hours in the"
              + " current months for all organizations.")
  @JsonIgnore
  public Long getTwolIngestedEventsBytesAggSum() {
    return twolIngestedEventsBytesAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TWOL_INGESTED_EVENTS_BYTES_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getTwolIngestedEventsBytesAggSum_JsonNullable() {
    return twolIngestedEventsBytesAggSum;
  }

  @JsonProperty(JSON_PROPERTY_TWOL_INGESTED_EVENTS_BYTES_AGG_SUM)
  public void setTwolIngestedEventsBytesAggSum_JsonNullable(
      JsonNullable<Long> twolIngestedEventsBytesAggSum) {
    this.twolIngestedEventsBytesAggSum = twolIngestedEventsBytesAggSum;
  }

  public void setTwolIngestedEventsBytesAggSum(Long twolIngestedEventsBytesAggSum) {
    this.twolIngestedEventsBytesAggSum = JsonNullable.<Long>of(twolIngestedEventsBytesAggSum);
  }

  public UsageSummaryResponse usage(List<UsageSummaryDate> usage) {
    this.usage = usage;
    return this;
  }

  public UsageSummaryResponse addUsageItem(UsageSummaryDate usageItem) {
    if (this.usage == null) {
      this.usage = new ArrayList<>();
    }
    this.usage.add(usageItem);
    return this;
  }

  /**
   * An array of objects regarding hourly usage.
   *
   * @return usage
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of objects regarding hourly usage.")
  @JsonProperty(JSON_PROPERTY_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<UsageSummaryDate> getUsage() {
    return usage;
  }

  public void setUsage(List<UsageSummaryDate> usage) {
    this.usage = usage;
  }

  public UsageSummaryResponse vsphereHostTop99pSum(Long vsphereHostTop99pSum) {
    this.vsphereHostTop99pSum = JsonNullable.<Long>of(vsphereHostTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all vSphere hosts over all hours in the current months for all
   * organizations.
   *
   * @return vsphereHostTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all vSphere hosts over all hours in the current months for"
              + " all organizations.")
  @JsonIgnore
  public Long getVsphereHostTop99pSum() {
    return vsphereHostTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VSPHERE_HOST_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getVsphereHostTop99pSum_JsonNullable() {
    return vsphereHostTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_VSPHERE_HOST_TOP99P_SUM)
  public void setVsphereHostTop99pSum_JsonNullable(JsonNullable<Long> vsphereHostTop99pSum) {
    this.vsphereHostTop99pSum = vsphereHostTop99pSum;
  }

  public void setVsphereHostTop99pSum(Long vsphereHostTop99pSum) {
    this.vsphereHostTop99pSum = JsonNullable.<Long>of(vsphereHostTop99pSum);
  }

  /** Return true if this UsageSummaryResponse object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageSummaryResponse usageSummaryResponse = (UsageSummaryResponse) o;
    return Objects.equals(this.agentHostTop99pSum, usageSummaryResponse.agentHostTop99pSum)
        && Objects.equals(
            this.apmAzureAppServiceHostTop99pSum,
            usageSummaryResponse.apmAzureAppServiceHostTop99pSum)
        && Objects.equals(this.apmHostTop99pSum, usageSummaryResponse.apmHostTop99pSum)
        && Objects.equals(this.awsHostTop99pSum, usageSummaryResponse.awsHostTop99pSum)
        && Objects.equals(this.awsLambdaFuncCount, usageSummaryResponse.awsLambdaFuncCount)
        && Objects.equals(
            this.awsLambdaInvocationsSum, usageSummaryResponse.awsLambdaInvocationsSum)
        && Objects.equals(
            this.azureAppServiceTop99pSum, usageSummaryResponse.azureAppServiceTop99pSum)
        && Objects.equals(this.azureHostTop99pSum, usageSummaryResponse.azureHostTop99pSum)
        && Objects.equals(
            this.billableIngestedBytesAggSum, usageSummaryResponse.billableIngestedBytesAggSum)
        && Objects.equals(
            this.complianceContainerAggSum, usageSummaryResponse.complianceContainerAggSum)
        && Objects.equals(this.complianceHostAggSum, usageSummaryResponse.complianceHostAggSum)
        && Objects.equals(this.containerAvgSum, usageSummaryResponse.containerAvgSum)
        && Objects.equals(this.containerHwmSum, usageSummaryResponse.containerHwmSum)
        && Objects.equals(this.customTsSum, usageSummaryResponse.customTsSum)
        && Objects.equals(this.endDate, usageSummaryResponse.endDate)
        && Objects.equals(
            this.fargateTasksCountAvgSum, usageSummaryResponse.fargateTasksCountAvgSum)
        && Objects.equals(
            this.fargateTasksCountHwmSum, usageSummaryResponse.fargateTasksCountHwmSum)
        && Objects.equals(this.gcpHostTop99pSum, usageSummaryResponse.gcpHostTop99pSum)
        && Objects.equals(this.herokuHostTop99pSum, usageSummaryResponse.herokuHostTop99pSum)
        && Objects.equals(
            this.incidentManagementMonthlyActiveUsersHwmSum,
            usageSummaryResponse.incidentManagementMonthlyActiveUsersHwmSum)
        && Objects.equals(
            this.indexedEventsCountAggSum, usageSummaryResponse.indexedEventsCountAggSum)
        && Objects.equals(this.infraHostTop99pSum, usageSummaryResponse.infraHostTop99pSum)
        && Objects.equals(
            this.ingestedEventsBytesAggSum, usageSummaryResponse.ingestedEventsBytesAggSum)
        && Objects.equals(this.iotDeviceAggSum, usageSummaryResponse.iotDeviceAggSum)
        && Objects.equals(this.iotDeviceTop99pSum, usageSummaryResponse.iotDeviceTop99pSum)
        && Objects.equals(this.lastUpdated, usageSummaryResponse.lastUpdated)
        && Objects.equals(
            this.liveIndexedEventsAggSum, usageSummaryResponse.liveIndexedEventsAggSum)
        && Objects.equals(
            this.liveIngestedBytesAggSum, usageSummaryResponse.liveIngestedBytesAggSum)
        && Objects.equals(
            this.mobileRumSessionCountAggSum, usageSummaryResponse.mobileRumSessionCountAggSum)
        && Objects.equals(
            this.mobileRumSessionCountAndroidAggSum,
            usageSummaryResponse.mobileRumSessionCountAndroidAggSum)
        && Objects.equals(
            this.mobileRumSessionCountIosAggSum,
            usageSummaryResponse.mobileRumSessionCountIosAggSum)
        && Objects.equals(
            this.netflowIndexedEventsCountAggSum,
            usageSummaryResponse.netflowIndexedEventsCountAggSum)
        && Objects.equals(this.npmHostTop99pSum, usageSummaryResponse.npmHostTop99pSum)
        && Objects.equals(
            this.opentelemetryHostTop99pSum, usageSummaryResponse.opentelemetryHostTop99pSum)
        && Objects.equals(
            this.profilingContainerAgentCountAvg,
            usageSummaryResponse.profilingContainerAgentCountAvg)
        && Objects.equals(
            this.profilingHostCountTop99pSum, usageSummaryResponse.profilingHostCountTop99pSum)
        && Objects.equals(
            this.rehydratedIndexedEventsAggSum, usageSummaryResponse.rehydratedIndexedEventsAggSum)
        && Objects.equals(
            this.rehydratedIngestedBytesAggSum, usageSummaryResponse.rehydratedIngestedBytesAggSum)
        && Objects.equals(this.rumSessionCountAggSum, usageSummaryResponse.rumSessionCountAggSum)
        && Objects.equals(
            this.rumTotalSessionCountAggSum, usageSummaryResponse.rumTotalSessionCountAggSum)
        && Objects.equals(this.startDate, usageSummaryResponse.startDate)
        && Objects.equals(
            this.syntheticsBrowserCheckCallsCountAggSum,
            usageSummaryResponse.syntheticsBrowserCheckCallsCountAggSum)
        && Objects.equals(
            this.syntheticsCheckCallsCountAggSum,
            usageSummaryResponse.syntheticsCheckCallsCountAggSum)
        && Objects.equals(
            this.traceSearchIndexedEventsCountAggSum,
            usageSummaryResponse.traceSearchIndexedEventsCountAggSum)
        && Objects.equals(
            this.twolIngestedEventsBytesAggSum, usageSummaryResponse.twolIngestedEventsBytesAggSum)
        && Objects.equals(this.usage, usageSummaryResponse.usage)
        && Objects.equals(this.vsphereHostTop99pSum, usageSummaryResponse.vsphereHostTop99pSum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        agentHostTop99pSum,
        apmAzureAppServiceHostTop99pSum,
        apmHostTop99pSum,
        awsHostTop99pSum,
        awsLambdaFuncCount,
        awsLambdaInvocationsSum,
        azureAppServiceTop99pSum,
        azureHostTop99pSum,
        billableIngestedBytesAggSum,
        complianceContainerAggSum,
        complianceHostAggSum,
        containerAvgSum,
        containerHwmSum,
        customTsSum,
        endDate,
        fargateTasksCountAvgSum,
        fargateTasksCountHwmSum,
        gcpHostTop99pSum,
        herokuHostTop99pSum,
        incidentManagementMonthlyActiveUsersHwmSum,
        indexedEventsCountAggSum,
        infraHostTop99pSum,
        ingestedEventsBytesAggSum,
        iotDeviceAggSum,
        iotDeviceTop99pSum,
        lastUpdated,
        liveIndexedEventsAggSum,
        liveIngestedBytesAggSum,
        mobileRumSessionCountAggSum,
        mobileRumSessionCountAndroidAggSum,
        mobileRumSessionCountIosAggSum,
        netflowIndexedEventsCountAggSum,
        npmHostTop99pSum,
        opentelemetryHostTop99pSum,
        profilingContainerAgentCountAvg,
        profilingHostCountTop99pSum,
        rehydratedIndexedEventsAggSum,
        rehydratedIngestedBytesAggSum,
        rumSessionCountAggSum,
        rumTotalSessionCountAggSum,
        startDate,
        syntheticsBrowserCheckCallsCountAggSum,
        syntheticsCheckCallsCountAggSum,
        traceSearchIndexedEventsCountAggSum,
        twolIngestedEventsBytesAggSum,
        usage,
        vsphereHostTop99pSum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageSummaryResponse {\n");
    sb.append("    agentHostTop99pSum: ").append(toIndentedString(agentHostTop99pSum)).append("\n");
    sb.append("    apmAzureAppServiceHostTop99pSum: ")
        .append(toIndentedString(apmAzureAppServiceHostTop99pSum))
        .append("\n");
    sb.append("    apmHostTop99pSum: ").append(toIndentedString(apmHostTop99pSum)).append("\n");
    sb.append("    awsHostTop99pSum: ").append(toIndentedString(awsHostTop99pSum)).append("\n");
    sb.append("    awsLambdaFuncCount: ").append(toIndentedString(awsLambdaFuncCount)).append("\n");
    sb.append("    awsLambdaInvocationsSum: ")
        .append(toIndentedString(awsLambdaInvocationsSum))
        .append("\n");
    sb.append("    azureAppServiceTop99pSum: ")
        .append(toIndentedString(azureAppServiceTop99pSum))
        .append("\n");
    sb.append("    azureHostTop99pSum: ").append(toIndentedString(azureHostTop99pSum)).append("\n");
    sb.append("    billableIngestedBytesAggSum: ")
        .append(toIndentedString(billableIngestedBytesAggSum))
        .append("\n");
    sb.append("    complianceContainerAggSum: ")
        .append(toIndentedString(complianceContainerAggSum))
        .append("\n");
    sb.append("    complianceHostAggSum: ")
        .append(toIndentedString(complianceHostAggSum))
        .append("\n");
    sb.append("    containerAvgSum: ").append(toIndentedString(containerAvgSum)).append("\n");
    sb.append("    containerHwmSum: ").append(toIndentedString(containerHwmSum)).append("\n");
    sb.append("    customTsSum: ").append(toIndentedString(customTsSum)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    fargateTasksCountAvgSum: ")
        .append(toIndentedString(fargateTasksCountAvgSum))
        .append("\n");
    sb.append("    fargateTasksCountHwmSum: ")
        .append(toIndentedString(fargateTasksCountHwmSum))
        .append("\n");
    sb.append("    gcpHostTop99pSum: ").append(toIndentedString(gcpHostTop99pSum)).append("\n");
    sb.append("    herokuHostTop99pSum: ")
        .append(toIndentedString(herokuHostTop99pSum))
        .append("\n");
    sb.append("    incidentManagementMonthlyActiveUsersHwmSum: ")
        .append(toIndentedString(incidentManagementMonthlyActiveUsersHwmSum))
        .append("\n");
    sb.append("    indexedEventsCountAggSum: ")
        .append(toIndentedString(indexedEventsCountAggSum))
        .append("\n");
    sb.append("    infraHostTop99pSum: ").append(toIndentedString(infraHostTop99pSum)).append("\n");
    sb.append("    ingestedEventsBytesAggSum: ")
        .append(toIndentedString(ingestedEventsBytesAggSum))
        .append("\n");
    sb.append("    iotDeviceAggSum: ").append(toIndentedString(iotDeviceAggSum)).append("\n");
    sb.append("    iotDeviceTop99pSum: ").append(toIndentedString(iotDeviceTop99pSum)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    liveIndexedEventsAggSum: ")
        .append(toIndentedString(liveIndexedEventsAggSum))
        .append("\n");
    sb.append("    liveIngestedBytesAggSum: ")
        .append(toIndentedString(liveIngestedBytesAggSum))
        .append("\n");
    sb.append("    mobileRumSessionCountAggSum: ")
        .append(toIndentedString(mobileRumSessionCountAggSum))
        .append("\n");
    sb.append("    mobileRumSessionCountAndroidAggSum: ")
        .append(toIndentedString(mobileRumSessionCountAndroidAggSum))
        .append("\n");
    sb.append("    mobileRumSessionCountIosAggSum: ")
        .append(toIndentedString(mobileRumSessionCountIosAggSum))
        .append("\n");
    sb.append("    netflowIndexedEventsCountAggSum: ")
        .append(toIndentedString(netflowIndexedEventsCountAggSum))
        .append("\n");
    sb.append("    npmHostTop99pSum: ").append(toIndentedString(npmHostTop99pSum)).append("\n");
    sb.append("    opentelemetryHostTop99pSum: ")
        .append(toIndentedString(opentelemetryHostTop99pSum))
        .append("\n");
    sb.append("    profilingContainerAgentCountAvg: ")
        .append(toIndentedString(profilingContainerAgentCountAvg))
        .append("\n");
    sb.append("    profilingHostCountTop99pSum: ")
        .append(toIndentedString(profilingHostCountTop99pSum))
        .append("\n");
    sb.append("    rehydratedIndexedEventsAggSum: ")
        .append(toIndentedString(rehydratedIndexedEventsAggSum))
        .append("\n");
    sb.append("    rehydratedIngestedBytesAggSum: ")
        .append(toIndentedString(rehydratedIngestedBytesAggSum))
        .append("\n");
    sb.append("    rumSessionCountAggSum: ")
        .append(toIndentedString(rumSessionCountAggSum))
        .append("\n");
    sb.append("    rumTotalSessionCountAggSum: ")
        .append(toIndentedString(rumTotalSessionCountAggSum))
        .append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    syntheticsBrowserCheckCallsCountAggSum: ")
        .append(toIndentedString(syntheticsBrowserCheckCallsCountAggSum))
        .append("\n");
    sb.append("    syntheticsCheckCallsCountAggSum: ")
        .append(toIndentedString(syntheticsCheckCallsCountAggSum))
        .append("\n");
    sb.append("    traceSearchIndexedEventsCountAggSum: ")
        .append(toIndentedString(traceSearchIndexedEventsCountAggSum))
        .append("\n");
    sb.append("    twolIngestedEventsBytesAggSum: ")
        .append(toIndentedString(twolIngestedEventsBytesAggSum))
        .append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("    vsphereHostTop99pSum: ")
        .append(toIndentedString(vsphereHostTop99pSum))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
