/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.datadog.api.v1.client.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

/** Global hourly report of all data billed by Datadog for a given organization. */
@ApiModel(
    description = "Global hourly report of all data billed by Datadog for a given organization.")
@JsonPropertyOrder({
  UsageSummaryDateOrg.JSON_PROPERTY_AGENT_HOST_TOP99P,
  UsageSummaryDateOrg.JSON_PROPERTY_APM_AZURE_APP_SERVICE_HOST_TOP99P,
  UsageSummaryDateOrg.JSON_PROPERTY_APM_HOST_TOP99P,
  UsageSummaryDateOrg.JSON_PROPERTY_AWS_HOST_TOP99P,
  UsageSummaryDateOrg.JSON_PROPERTY_AWS_LAMBDA_FUNC_COUNT,
  UsageSummaryDateOrg.JSON_PROPERTY_AWS_LAMBDA_INVOCATIONS_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_AZURE_APP_SERVICE_TOP99P,
  UsageSummaryDateOrg.JSON_PROPERTY_BILLABLE_INGESTED_BYTES_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_COMPLIANCE_CONTAINER_AGG_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_COMPLIANCE_HOST_AGG_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_CONTAINER_AVG,
  UsageSummaryDateOrg.JSON_PROPERTY_CONTAINER_HWM,
  UsageSummaryDateOrg.JSON_PROPERTY_CUSTOM_TS_AVG,
  UsageSummaryDateOrg.JSON_PROPERTY_FARGATE_TASKS_COUNT_AVG,
  UsageSummaryDateOrg.JSON_PROPERTY_FARGATE_TASKS_COUNT_HWM,
  UsageSummaryDateOrg.JSON_PROPERTY_GCP_HOST_TOP99P,
  UsageSummaryDateOrg.JSON_PROPERTY_HEROKU_HOST_TOP99P,
  UsageSummaryDateOrg.JSON_PROPERTY_ID,
  UsageSummaryDateOrg.JSON_PROPERTY_INCIDENT_MANAGEMENT_MONTHLY_ACTIVE_USERS_HWM,
  UsageSummaryDateOrg.JSON_PROPERTY_INDEXED_EVENTS_COUNT_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_INFRA_HOST_TOP99P,
  UsageSummaryDateOrg.JSON_PROPERTY_INGESTED_EVENTS_BYTES_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_IOT_DEVICE_AGG_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_IOT_DEVICE_TOP99P_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_ANDROID_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_IOS_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_NAME,
  UsageSummaryDateOrg.JSON_PROPERTY_NETFLOW_INDEXED_EVENTS_COUNT_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_NPM_HOST_TOP99P,
  UsageSummaryDateOrg.JSON_PROPERTY_OPENTELEMETRY_HOST_TOP99P,
  UsageSummaryDateOrg.JSON_PROPERTY_PROFILING_HOST_TOP99P,
  UsageSummaryDateOrg.JSON_PROPERTY_PUBLIC_ID,
  UsageSummaryDateOrg.JSON_PROPERTY_RUM_SESSION_COUNT_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_RUM_TOTAL_SESSION_COUNT_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_SYNTHETICS_BROWSER_CHECK_CALLS_COUNT_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_SYNTHETICS_CHECK_CALLS_COUNT_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_TRACE_SEARCH_INDEXED_EVENTS_COUNT_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_TWOL_INGESTED_EVENTS_BYTES_SUM,
  UsageSummaryDateOrg.JSON_PROPERTY_VSPHERE_HOST_TOP99P
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UsageSummaryDateOrg {
  public static final String JSON_PROPERTY_AGENT_HOST_TOP99P = "agent_host_top99p";
  private JsonNullable<Long> agentHostTop99p = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_APM_AZURE_APP_SERVICE_HOST_TOP99P =
      "apm_azure_app_service_host_top99p";
  private JsonNullable<Long> apmAzureAppServiceHostTop99p = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_APM_HOST_TOP99P = "apm_host_top99p";
  private JsonNullable<Long> apmHostTop99p = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_AWS_HOST_TOP99P = "aws_host_top99p";
  private JsonNullable<Long> awsHostTop99p = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_AWS_LAMBDA_FUNC_COUNT = "aws_lambda_func_count";
  private JsonNullable<Long> awsLambdaFuncCount = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_AWS_LAMBDA_INVOCATIONS_SUM =
      "aws_lambda_invocations_sum";
  private JsonNullable<Long> awsLambdaInvocationsSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_AZURE_APP_SERVICE_TOP99P = "azure_app_service_top99p";
  private JsonNullable<Long> azureAppServiceTop99p = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_BILLABLE_INGESTED_BYTES_SUM =
      "billable_ingested_bytes_sum";
  private JsonNullable<Long> billableIngestedBytesSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_COMPLIANCE_CONTAINER_AGG_SUM =
      "compliance_container_agg_sum";
  private JsonNullable<Long> complianceContainerAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_COMPLIANCE_HOST_AGG_SUM = "compliance_host_agg_sum";
  private JsonNullable<Long> complianceHostAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_CONTAINER_AVG = "container_avg";
  private JsonNullable<Long> containerAvg = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_CONTAINER_HWM = "container_hwm";
  private JsonNullable<Long> containerHwm = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_CUSTOM_TS_AVG = "custom_ts_avg";
  private JsonNullable<Long> customTsAvg = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_FARGATE_TASKS_COUNT_AVG = "fargate_tasks_count_avg";
  private JsonNullable<Long> fargateTasksCountAvg = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_FARGATE_TASKS_COUNT_HWM = "fargate_tasks_count_hwm";
  private JsonNullable<Long> fargateTasksCountHwm = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_GCP_HOST_TOP99P = "gcp_host_top99p";
  private JsonNullable<Long> gcpHostTop99p = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_HEROKU_HOST_TOP99P = "heroku_host_top99p";
  private JsonNullable<Long> herokuHostTop99p = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_INCIDENT_MANAGEMENT_MONTHLY_ACTIVE_USERS_HWM =
      "incident_management_monthly_active_users_hwm";
  private JsonNullable<Long> incidentManagementMonthlyActiveUsersHwm =
      JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_INDEXED_EVENTS_COUNT_SUM = "indexed_events_count_sum";
  private JsonNullable<Long> indexedEventsCountSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_INFRA_HOST_TOP99P = "infra_host_top99p";
  private JsonNullable<Long> infraHostTop99p = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_INGESTED_EVENTS_BYTES_SUM = "ingested_events_bytes_sum";
  private JsonNullable<Long> ingestedEventsBytesSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_IOT_DEVICE_AGG_SUM = "iot_device_agg_sum";
  private JsonNullable<Long> iotDeviceAggSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_IOT_DEVICE_TOP99P_SUM = "iot_device_top99p_sum";
  private JsonNullable<Long> iotDeviceTop99pSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_ANDROID_SUM =
      "mobile_rum_session_count_android_sum";
  private JsonNullable<Long> mobileRumSessionCountAndroidSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_IOS_SUM =
      "mobile_rum_session_count_ios_sum";
  private JsonNullable<Long> mobileRumSessionCountIosSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_SUM =
      "mobile_rum_session_count_sum";
  private JsonNullable<Long> mobileRumSessionCountSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_NETFLOW_INDEXED_EVENTS_COUNT_SUM =
      "netflow_indexed_events_count_sum";
  private JsonNullable<Long> netflowIndexedEventsCountSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_NPM_HOST_TOP99P = "npm_host_top99p";
  private JsonNullable<Long> npmHostTop99p = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_OPENTELEMETRY_HOST_TOP99P = "opentelemetry_host_top99p";
  private JsonNullable<Long> opentelemetryHostTop99p = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_PROFILING_HOST_TOP99P = "profiling_host_top99p";
  private JsonNullable<Long> profilingHostTop99p = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_PUBLIC_ID = "public_id";
  private String publicId;

  public static final String JSON_PROPERTY_RUM_SESSION_COUNT_SUM = "rum_session_count_sum";
  private JsonNullable<Long> rumSessionCountSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_RUM_TOTAL_SESSION_COUNT_SUM =
      "rum_total_session_count_sum";
  private JsonNullable<Long> rumTotalSessionCountSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_SYNTHETICS_BROWSER_CHECK_CALLS_COUNT_SUM =
      "synthetics_browser_check_calls_count_sum";
  private JsonNullable<Long> syntheticsBrowserCheckCallsCountSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_SYNTHETICS_CHECK_CALLS_COUNT_SUM =
      "synthetics_check_calls_count_sum";
  private JsonNullable<Long> syntheticsCheckCallsCountSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_TRACE_SEARCH_INDEXED_EVENTS_COUNT_SUM =
      "trace_search_indexed_events_count_sum";
  private JsonNullable<Long> traceSearchIndexedEventsCountSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_TWOL_INGESTED_EVENTS_BYTES_SUM =
      "twol_ingested_events_bytes_sum";
  private JsonNullable<Long> twolIngestedEventsBytesSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_VSPHERE_HOST_TOP99P = "vsphere_host_top99p";
  private JsonNullable<Long> vsphereHostTop99p = JsonNullable.<Long>undefined();

  public UsageSummaryDateOrg agentHostTop99p(Long agentHostTop99p) {
    this.agentHostTop99p = JsonNullable.<Long>of(agentHostTop99p);
    return this;
  }

  /**
   * Shows the 99th percentile of all agent hosts over all hours in the current date for the given
   * org.
   *
   * @return agentHostTop99p
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all agent hosts over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getAgentHostTop99p() {
    return agentHostTop99p.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AGENT_HOST_TOP99P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getAgentHostTop99p_JsonNullable() {
    return agentHostTop99p;
  }

  @JsonProperty(JSON_PROPERTY_AGENT_HOST_TOP99P)
  public void setAgentHostTop99p_JsonNullable(JsonNullable<Long> agentHostTop99p) {
    this.agentHostTop99p = agentHostTop99p;
  }

  public void setAgentHostTop99p(Long agentHostTop99p) {
    this.agentHostTop99p = JsonNullable.<Long>of(agentHostTop99p);
  }

  public UsageSummaryDateOrg apmAzureAppServiceHostTop99p(Long apmAzureAppServiceHostTop99p) {
    this.apmAzureAppServiceHostTop99p = JsonNullable.<Long>of(apmAzureAppServiceHostTop99p);
    return this;
  }

  /**
   * Shows the 99th percentile of all Azure app services using APM over all hours in the current
   * date for the given org.
   *
   * @return apmAzureAppServiceHostTop99p
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all Azure app services using APM over all hours in the"
              + " current date for the given org.")
  @JsonIgnore
  public Long getApmAzureAppServiceHostTop99p() {
    return apmAzureAppServiceHostTop99p.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_APM_AZURE_APP_SERVICE_HOST_TOP99P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getApmAzureAppServiceHostTop99p_JsonNullable() {
    return apmAzureAppServiceHostTop99p;
  }

  @JsonProperty(JSON_PROPERTY_APM_AZURE_APP_SERVICE_HOST_TOP99P)
  public void setApmAzureAppServiceHostTop99p_JsonNullable(
      JsonNullable<Long> apmAzureAppServiceHostTop99p) {
    this.apmAzureAppServiceHostTop99p = apmAzureAppServiceHostTop99p;
  }

  public void setApmAzureAppServiceHostTop99p(Long apmAzureAppServiceHostTop99p) {
    this.apmAzureAppServiceHostTop99p = JsonNullable.<Long>of(apmAzureAppServiceHostTop99p);
  }

  public UsageSummaryDateOrg apmHostTop99p(Long apmHostTop99p) {
    this.apmHostTop99p = JsonNullable.<Long>of(apmHostTop99p);
    return this;
  }

  /**
   * Shows the 99th percentile of all distinct APM hosts over all hours in the current date for the
   * given org.
   *
   * @return apmHostTop99p
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all distinct APM hosts over all hours in the current date"
              + " for the given org.")
  @JsonIgnore
  public Long getApmHostTop99p() {
    return apmHostTop99p.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_APM_HOST_TOP99P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getApmHostTop99p_JsonNullable() {
    return apmHostTop99p;
  }

  @JsonProperty(JSON_PROPERTY_APM_HOST_TOP99P)
  public void setApmHostTop99p_JsonNullable(JsonNullable<Long> apmHostTop99p) {
    this.apmHostTop99p = apmHostTop99p;
  }

  public void setApmHostTop99p(Long apmHostTop99p) {
    this.apmHostTop99p = JsonNullable.<Long>of(apmHostTop99p);
  }

  public UsageSummaryDateOrg awsHostTop99p(Long awsHostTop99p) {
    this.awsHostTop99p = JsonNullable.<Long>of(awsHostTop99p);
    return this;
  }

  /**
   * Shows the 99th percentile of all AWS hosts over all hours in the current date for the given
   * org.
   *
   * @return awsHostTop99p
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all AWS hosts over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getAwsHostTop99p() {
    return awsHostTop99p.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AWS_HOST_TOP99P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getAwsHostTop99p_JsonNullable() {
    return awsHostTop99p;
  }

  @JsonProperty(JSON_PROPERTY_AWS_HOST_TOP99P)
  public void setAwsHostTop99p_JsonNullable(JsonNullable<Long> awsHostTop99p) {
    this.awsHostTop99p = awsHostTop99p;
  }

  public void setAwsHostTop99p(Long awsHostTop99p) {
    this.awsHostTop99p = JsonNullable.<Long>of(awsHostTop99p);
  }

  public UsageSummaryDateOrg awsLambdaFuncCount(Long awsLambdaFuncCount) {
    this.awsLambdaFuncCount = JsonNullable.<Long>of(awsLambdaFuncCount);
    return this;
  }

  /**
   * Shows the sum of all AWS Lambda invocations over all hours in the current date for the given
   * org.
   *
   * @return awsLambdaFuncCount
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all AWS Lambda invocations over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getAwsLambdaFuncCount() {
    return awsLambdaFuncCount.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AWS_LAMBDA_FUNC_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getAwsLambdaFuncCount_JsonNullable() {
    return awsLambdaFuncCount;
  }

  @JsonProperty(JSON_PROPERTY_AWS_LAMBDA_FUNC_COUNT)
  public void setAwsLambdaFuncCount_JsonNullable(JsonNullable<Long> awsLambdaFuncCount) {
    this.awsLambdaFuncCount = awsLambdaFuncCount;
  }

  public void setAwsLambdaFuncCount(Long awsLambdaFuncCount) {
    this.awsLambdaFuncCount = JsonNullable.<Long>of(awsLambdaFuncCount);
  }

  public UsageSummaryDateOrg awsLambdaInvocationsSum(Long awsLambdaInvocationsSum) {
    this.awsLambdaInvocationsSum = JsonNullable.<Long>of(awsLambdaInvocationsSum);
    return this;
  }

  /**
   * Shows the sum of all AWS Lambda invocations over all hours in the current date for the given
   * org.
   *
   * @return awsLambdaInvocationsSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all AWS Lambda invocations over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getAwsLambdaInvocationsSum() {
    return awsLambdaInvocationsSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AWS_LAMBDA_INVOCATIONS_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getAwsLambdaInvocationsSum_JsonNullable() {
    return awsLambdaInvocationsSum;
  }

  @JsonProperty(JSON_PROPERTY_AWS_LAMBDA_INVOCATIONS_SUM)
  public void setAwsLambdaInvocationsSum_JsonNullable(JsonNullable<Long> awsLambdaInvocationsSum) {
    this.awsLambdaInvocationsSum = awsLambdaInvocationsSum;
  }

  public void setAwsLambdaInvocationsSum(Long awsLambdaInvocationsSum) {
    this.awsLambdaInvocationsSum = JsonNullable.<Long>of(awsLambdaInvocationsSum);
  }

  public UsageSummaryDateOrg azureAppServiceTop99p(Long azureAppServiceTop99p) {
    this.azureAppServiceTop99p = JsonNullable.<Long>of(azureAppServiceTop99p);
    return this;
  }

  /**
   * Shows the 99th percentile of all Azure app services over all hours in the current date for the
   * given org.
   *
   * @return azureAppServiceTop99p
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all Azure app services over all hours in the current date"
              + " for the given org.")
  @JsonIgnore
  public Long getAzureAppServiceTop99p() {
    return azureAppServiceTop99p.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AZURE_APP_SERVICE_TOP99P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getAzureAppServiceTop99p_JsonNullable() {
    return azureAppServiceTop99p;
  }

  @JsonProperty(JSON_PROPERTY_AZURE_APP_SERVICE_TOP99P)
  public void setAzureAppServiceTop99p_JsonNullable(JsonNullable<Long> azureAppServiceTop99p) {
    this.azureAppServiceTop99p = azureAppServiceTop99p;
  }

  public void setAzureAppServiceTop99p(Long azureAppServiceTop99p) {
    this.azureAppServiceTop99p = JsonNullable.<Long>of(azureAppServiceTop99p);
  }

  public UsageSummaryDateOrg billableIngestedBytesSum(Long billableIngestedBytesSum) {
    this.billableIngestedBytesSum = JsonNullable.<Long>of(billableIngestedBytesSum);
    return this;
  }

  /**
   * Shows the sum of all log bytes ingested over all hours in the current date for the given org.
   *
   * @return billableIngestedBytesSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all log bytes ingested over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getBillableIngestedBytesSum() {
    return billableIngestedBytesSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_BILLABLE_INGESTED_BYTES_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getBillableIngestedBytesSum_JsonNullable() {
    return billableIngestedBytesSum;
  }

  @JsonProperty(JSON_PROPERTY_BILLABLE_INGESTED_BYTES_SUM)
  public void setBillableIngestedBytesSum_JsonNullable(
      JsonNullable<Long> billableIngestedBytesSum) {
    this.billableIngestedBytesSum = billableIngestedBytesSum;
  }

  public void setBillableIngestedBytesSum(Long billableIngestedBytesSum) {
    this.billableIngestedBytesSum = JsonNullable.<Long>of(billableIngestedBytesSum);
  }

  public UsageSummaryDateOrg complianceContainerAggSum(Long complianceContainerAggSum) {
    this.complianceContainerAggSum = JsonNullable.<Long>of(complianceContainerAggSum);
    return this;
  }

  /**
   * Shows the sum of all compliance containers over all hours in the current date for the given
   * org.
   *
   * @return complianceContainerAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all compliance containers over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getComplianceContainerAggSum() {
    return complianceContainerAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMPLIANCE_CONTAINER_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getComplianceContainerAggSum_JsonNullable() {
    return complianceContainerAggSum;
  }

  @JsonProperty(JSON_PROPERTY_COMPLIANCE_CONTAINER_AGG_SUM)
  public void setComplianceContainerAggSum_JsonNullable(
      JsonNullable<Long> complianceContainerAggSum) {
    this.complianceContainerAggSum = complianceContainerAggSum;
  }

  public void setComplianceContainerAggSum(Long complianceContainerAggSum) {
    this.complianceContainerAggSum = JsonNullable.<Long>of(complianceContainerAggSum);
  }

  public UsageSummaryDateOrg complianceHostAggSum(Long complianceHostAggSum) {
    this.complianceHostAggSum = JsonNullable.<Long>of(complianceHostAggSum);
    return this;
  }

  /**
   * Shows the sum of all compliance hosts over all hours in the current date for the given org.
   *
   * @return complianceHostAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all compliance hosts over all hours in the current date for the given"
              + " org.")
  @JsonIgnore
  public Long getComplianceHostAggSum() {
    return complianceHostAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMPLIANCE_HOST_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getComplianceHostAggSum_JsonNullable() {
    return complianceHostAggSum;
  }

  @JsonProperty(JSON_PROPERTY_COMPLIANCE_HOST_AGG_SUM)
  public void setComplianceHostAggSum_JsonNullable(JsonNullable<Long> complianceHostAggSum) {
    this.complianceHostAggSum = complianceHostAggSum;
  }

  public void setComplianceHostAggSum(Long complianceHostAggSum) {
    this.complianceHostAggSum = JsonNullable.<Long>of(complianceHostAggSum);
  }

  public UsageSummaryDateOrg containerAvg(Long containerAvg) {
    this.containerAvg = JsonNullable.<Long>of(containerAvg);
    return this;
  }

  /**
   * Shows the average of all distinct containers over all hours in the current date for the given
   * org.
   *
   * @return containerAvg
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the average of all distinct containers over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getContainerAvg() {
    return containerAvg.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONTAINER_AVG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getContainerAvg_JsonNullable() {
    return containerAvg;
  }

  @JsonProperty(JSON_PROPERTY_CONTAINER_AVG)
  public void setContainerAvg_JsonNullable(JsonNullable<Long> containerAvg) {
    this.containerAvg = containerAvg;
  }

  public void setContainerAvg(Long containerAvg) {
    this.containerAvg = JsonNullable.<Long>of(containerAvg);
  }

  public UsageSummaryDateOrg containerHwm(Long containerHwm) {
    this.containerHwm = JsonNullable.<Long>of(containerHwm);
    return this;
  }

  /**
   * Shows the high-water mark of all distinct containers over all hours in the current date for the
   * given org.
   *
   * @return containerHwm
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the high-water mark of all distinct containers over all hours in the current date"
              + " for the given org.")
  @JsonIgnore
  public Long getContainerHwm() {
    return containerHwm.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONTAINER_HWM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getContainerHwm_JsonNullable() {
    return containerHwm;
  }

  @JsonProperty(JSON_PROPERTY_CONTAINER_HWM)
  public void setContainerHwm_JsonNullable(JsonNullable<Long> containerHwm) {
    this.containerHwm = containerHwm;
  }

  public void setContainerHwm(Long containerHwm) {
    this.containerHwm = JsonNullable.<Long>of(containerHwm);
  }

  public UsageSummaryDateOrg customTsAvg(Long customTsAvg) {
    this.customTsAvg = JsonNullable.<Long>of(customTsAvg);
    return this;
  }

  /**
   * Shows the average number of distinct custom metrics over all hours in the current date for the
   * given org.
   *
   * @return customTsAvg
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the average number of distinct custom metrics over all hours in the current date"
              + " for the given org.")
  @JsonIgnore
  public Long getCustomTsAvg() {
    return customTsAvg.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CUSTOM_TS_AVG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getCustomTsAvg_JsonNullable() {
    return customTsAvg;
  }

  @JsonProperty(JSON_PROPERTY_CUSTOM_TS_AVG)
  public void setCustomTsAvg_JsonNullable(JsonNullable<Long> customTsAvg) {
    this.customTsAvg = customTsAvg;
  }

  public void setCustomTsAvg(Long customTsAvg) {
    this.customTsAvg = JsonNullable.<Long>of(customTsAvg);
  }

  public UsageSummaryDateOrg fargateTasksCountAvg(Long fargateTasksCountAvg) {
    this.fargateTasksCountAvg = JsonNullable.<Long>of(fargateTasksCountAvg);
    return this;
  }

  /**
   * The average task count for Fargate.
   *
   * @return fargateTasksCountAvg
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The average task count for Fargate.")
  @JsonIgnore
  public Long getFargateTasksCountAvg() {
    return fargateTasksCountAvg.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FARGATE_TASKS_COUNT_AVG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getFargateTasksCountAvg_JsonNullable() {
    return fargateTasksCountAvg;
  }

  @JsonProperty(JSON_PROPERTY_FARGATE_TASKS_COUNT_AVG)
  public void setFargateTasksCountAvg_JsonNullable(JsonNullable<Long> fargateTasksCountAvg) {
    this.fargateTasksCountAvg = fargateTasksCountAvg;
  }

  public void setFargateTasksCountAvg(Long fargateTasksCountAvg) {
    this.fargateTasksCountAvg = JsonNullable.<Long>of(fargateTasksCountAvg);
  }

  public UsageSummaryDateOrg fargateTasksCountHwm(Long fargateTasksCountHwm) {
    this.fargateTasksCountHwm = JsonNullable.<Long>of(fargateTasksCountHwm);
    return this;
  }

  /**
   * Shows the high-water mark of all Fargate tasks over all hours in the current date for the given
   * org.
   *
   * @return fargateTasksCountHwm
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the high-water mark of all Fargate tasks over all hours in the current date for"
              + " the given org.")
  @JsonIgnore
  public Long getFargateTasksCountHwm() {
    return fargateTasksCountHwm.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FARGATE_TASKS_COUNT_HWM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getFargateTasksCountHwm_JsonNullable() {
    return fargateTasksCountHwm;
  }

  @JsonProperty(JSON_PROPERTY_FARGATE_TASKS_COUNT_HWM)
  public void setFargateTasksCountHwm_JsonNullable(JsonNullable<Long> fargateTasksCountHwm) {
    this.fargateTasksCountHwm = fargateTasksCountHwm;
  }

  public void setFargateTasksCountHwm(Long fargateTasksCountHwm) {
    this.fargateTasksCountHwm = JsonNullable.<Long>of(fargateTasksCountHwm);
  }

  public UsageSummaryDateOrg gcpHostTop99p(Long gcpHostTop99p) {
    this.gcpHostTop99p = JsonNullable.<Long>of(gcpHostTop99p);
    return this;
  }

  /**
   * Shows the 99th percentile of all GCP hosts over all hours in the current date for the given
   * org.
   *
   * @return gcpHostTop99p
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all GCP hosts over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getGcpHostTop99p() {
    return gcpHostTop99p.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_GCP_HOST_TOP99P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getGcpHostTop99p_JsonNullable() {
    return gcpHostTop99p;
  }

  @JsonProperty(JSON_PROPERTY_GCP_HOST_TOP99P)
  public void setGcpHostTop99p_JsonNullable(JsonNullable<Long> gcpHostTop99p) {
    this.gcpHostTop99p = gcpHostTop99p;
  }

  public void setGcpHostTop99p(Long gcpHostTop99p) {
    this.gcpHostTop99p = JsonNullable.<Long>of(gcpHostTop99p);
  }

  public UsageSummaryDateOrg herokuHostTop99p(Long herokuHostTop99p) {
    this.herokuHostTop99p = JsonNullable.<Long>of(herokuHostTop99p);
    return this;
  }

  /**
   * Shows the 99th percentile of all Heroku dynos over all hours in the current date for the given
   * org.
   *
   * @return herokuHostTop99p
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all Heroku dynos over all hours in the current date for"
              + " the given org.")
  @JsonIgnore
  public Long getHerokuHostTop99p() {
    return herokuHostTop99p.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_HEROKU_HOST_TOP99P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getHerokuHostTop99p_JsonNullable() {
    return herokuHostTop99p;
  }

  @JsonProperty(JSON_PROPERTY_HEROKU_HOST_TOP99P)
  public void setHerokuHostTop99p_JsonNullable(JsonNullable<Long> herokuHostTop99p) {
    this.herokuHostTop99p = herokuHostTop99p;
  }

  public void setHerokuHostTop99p(Long herokuHostTop99p) {
    this.herokuHostTop99p = JsonNullable.<Long>of(herokuHostTop99p);
  }

  public UsageSummaryDateOrg id(String id) {
    this.id = id;
    return this;
  }

  /**
   * The organization id.
   *
   * @return id
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The organization id.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UsageSummaryDateOrg incidentManagementMonthlyActiveUsersHwm(
      Long incidentManagementMonthlyActiveUsersHwm) {
    this.incidentManagementMonthlyActiveUsersHwm =
        JsonNullable.<Long>of(incidentManagementMonthlyActiveUsersHwm);
    return this;
  }

  /**
   * Shows the high-water mark of incident management monthly active users over all hours in the
   * current date for the given org.
   *
   * @return incidentManagementMonthlyActiveUsersHwm
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the high-water mark of incident management monthly active users over all hours in"
              + " the current date for the given org.")
  @JsonIgnore
  public Long getIncidentManagementMonthlyActiveUsersHwm() {
    return incidentManagementMonthlyActiveUsersHwm.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INCIDENT_MANAGEMENT_MONTHLY_ACTIVE_USERS_HWM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getIncidentManagementMonthlyActiveUsersHwm_JsonNullable() {
    return incidentManagementMonthlyActiveUsersHwm;
  }

  @JsonProperty(JSON_PROPERTY_INCIDENT_MANAGEMENT_MONTHLY_ACTIVE_USERS_HWM)
  public void setIncidentManagementMonthlyActiveUsersHwm_JsonNullable(
      JsonNullable<Long> incidentManagementMonthlyActiveUsersHwm) {
    this.incidentManagementMonthlyActiveUsersHwm = incidentManagementMonthlyActiveUsersHwm;
  }

  public void setIncidentManagementMonthlyActiveUsersHwm(
      Long incidentManagementMonthlyActiveUsersHwm) {
    this.incidentManagementMonthlyActiveUsersHwm =
        JsonNullable.<Long>of(incidentManagementMonthlyActiveUsersHwm);
  }

  public UsageSummaryDateOrg indexedEventsCountSum(Long indexedEventsCountSum) {
    this.indexedEventsCountSum = JsonNullable.<Long>of(indexedEventsCountSum);
    return this;
  }

  /**
   * Shows the sum of all log events indexed over all hours in the current date for the given org.
   *
   * @return indexedEventsCountSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all log events indexed over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getIndexedEventsCountSum() {
    return indexedEventsCountSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INDEXED_EVENTS_COUNT_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getIndexedEventsCountSum_JsonNullable() {
    return indexedEventsCountSum;
  }

  @JsonProperty(JSON_PROPERTY_INDEXED_EVENTS_COUNT_SUM)
  public void setIndexedEventsCountSum_JsonNullable(JsonNullable<Long> indexedEventsCountSum) {
    this.indexedEventsCountSum = indexedEventsCountSum;
  }

  public void setIndexedEventsCountSum(Long indexedEventsCountSum) {
    this.indexedEventsCountSum = JsonNullable.<Long>of(indexedEventsCountSum);
  }

  public UsageSummaryDateOrg infraHostTop99p(Long infraHostTop99p) {
    this.infraHostTop99p = JsonNullable.<Long>of(infraHostTop99p);
    return this;
  }

  /**
   * Shows the 99th percentile of all distinct infrastructure hosts over all hours in the current
   * date for the given org.
   *
   * @return infraHostTop99p
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all distinct infrastructure hosts over all hours in the"
              + " current date for the given org.")
  @JsonIgnore
  public Long getInfraHostTop99p() {
    return infraHostTop99p.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INFRA_HOST_TOP99P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getInfraHostTop99p_JsonNullable() {
    return infraHostTop99p;
  }

  @JsonProperty(JSON_PROPERTY_INFRA_HOST_TOP99P)
  public void setInfraHostTop99p_JsonNullable(JsonNullable<Long> infraHostTop99p) {
    this.infraHostTop99p = infraHostTop99p;
  }

  public void setInfraHostTop99p(Long infraHostTop99p) {
    this.infraHostTop99p = JsonNullable.<Long>of(infraHostTop99p);
  }

  public UsageSummaryDateOrg ingestedEventsBytesSum(Long ingestedEventsBytesSum) {
    this.ingestedEventsBytesSum = JsonNullable.<Long>of(ingestedEventsBytesSum);
    return this;
  }

  /**
   * Shows the sum of all log bytes ingested over all hours in the current date for the given org.
   *
   * @return ingestedEventsBytesSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all log bytes ingested over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getIngestedEventsBytesSum() {
    return ingestedEventsBytesSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INGESTED_EVENTS_BYTES_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getIngestedEventsBytesSum_JsonNullable() {
    return ingestedEventsBytesSum;
  }

  @JsonProperty(JSON_PROPERTY_INGESTED_EVENTS_BYTES_SUM)
  public void setIngestedEventsBytesSum_JsonNullable(JsonNullable<Long> ingestedEventsBytesSum) {
    this.ingestedEventsBytesSum = ingestedEventsBytesSum;
  }

  public void setIngestedEventsBytesSum(Long ingestedEventsBytesSum) {
    this.ingestedEventsBytesSum = JsonNullable.<Long>of(ingestedEventsBytesSum);
  }

  public UsageSummaryDateOrg iotDeviceAggSum(Long iotDeviceAggSum) {
    this.iotDeviceAggSum = JsonNullable.<Long>of(iotDeviceAggSum);
    return this;
  }

  /**
   * Shows the sum of all IoT devices over all hours in the current date for the given org.
   *
   * @return iotDeviceAggSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all IoT devices over all hours in the current date for the given org.")
  @JsonIgnore
  public Long getIotDeviceAggSum() {
    return iotDeviceAggSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IOT_DEVICE_AGG_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getIotDeviceAggSum_JsonNullable() {
    return iotDeviceAggSum;
  }

  @JsonProperty(JSON_PROPERTY_IOT_DEVICE_AGG_SUM)
  public void setIotDeviceAggSum_JsonNullable(JsonNullable<Long> iotDeviceAggSum) {
    this.iotDeviceAggSum = iotDeviceAggSum;
  }

  public void setIotDeviceAggSum(Long iotDeviceAggSum) {
    this.iotDeviceAggSum = JsonNullable.<Long>of(iotDeviceAggSum);
  }

  public UsageSummaryDateOrg iotDeviceTop99pSum(Long iotDeviceTop99pSum) {
    this.iotDeviceTop99pSum = JsonNullable.<Long>of(iotDeviceTop99pSum);
    return this;
  }

  /**
   * Shows the 99th percentile of all IoT devices over all hours in the current date for the given
   * org.
   *
   * @return iotDeviceTop99pSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all IoT devices over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getIotDeviceTop99pSum() {
    return iotDeviceTop99pSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IOT_DEVICE_TOP99P_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getIotDeviceTop99pSum_JsonNullable() {
    return iotDeviceTop99pSum;
  }

  @JsonProperty(JSON_PROPERTY_IOT_DEVICE_TOP99P_SUM)
  public void setIotDeviceTop99pSum_JsonNullable(JsonNullable<Long> iotDeviceTop99pSum) {
    this.iotDeviceTop99pSum = iotDeviceTop99pSum;
  }

  public void setIotDeviceTop99pSum(Long iotDeviceTop99pSum) {
    this.iotDeviceTop99pSum = JsonNullable.<Long>of(iotDeviceTop99pSum);
  }

  public UsageSummaryDateOrg mobileRumSessionCountAndroidSum(Long mobileRumSessionCountAndroidSum) {
    this.mobileRumSessionCountAndroidSum = JsonNullable.<Long>of(mobileRumSessionCountAndroidSum);
    return this;
  }

  /**
   * Shows the sum of all mobile RUM Sessions on Android over all hours in the current date for the
   * given org.
   *
   * @return mobileRumSessionCountAndroidSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all mobile RUM Sessions on Android over all hours in the current date"
              + " for the given org.")
  @JsonIgnore
  public Long getMobileRumSessionCountAndroidSum() {
    return mobileRumSessionCountAndroidSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_ANDROID_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getMobileRumSessionCountAndroidSum_JsonNullable() {
    return mobileRumSessionCountAndroidSum;
  }

  @JsonProperty(JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_ANDROID_SUM)
  public void setMobileRumSessionCountAndroidSum_JsonNullable(
      JsonNullable<Long> mobileRumSessionCountAndroidSum) {
    this.mobileRumSessionCountAndroidSum = mobileRumSessionCountAndroidSum;
  }

  public void setMobileRumSessionCountAndroidSum(Long mobileRumSessionCountAndroidSum) {
    this.mobileRumSessionCountAndroidSum = JsonNullable.<Long>of(mobileRumSessionCountAndroidSum);
  }

  public UsageSummaryDateOrg mobileRumSessionCountIosSum(Long mobileRumSessionCountIosSum) {
    this.mobileRumSessionCountIosSum = JsonNullable.<Long>of(mobileRumSessionCountIosSum);
    return this;
  }

  /**
   * Shows the sum of all mobile RUM Sessions on iOS over all hours in the current date for the
   * given org.
   *
   * @return mobileRumSessionCountIosSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all mobile RUM Sessions on iOS over all hours in the current date for"
              + " the given org.")
  @JsonIgnore
  public Long getMobileRumSessionCountIosSum() {
    return mobileRumSessionCountIosSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_IOS_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getMobileRumSessionCountIosSum_JsonNullable() {
    return mobileRumSessionCountIosSum;
  }

  @JsonProperty(JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_IOS_SUM)
  public void setMobileRumSessionCountIosSum_JsonNullable(
      JsonNullable<Long> mobileRumSessionCountIosSum) {
    this.mobileRumSessionCountIosSum = mobileRumSessionCountIosSum;
  }

  public void setMobileRumSessionCountIosSum(Long mobileRumSessionCountIosSum) {
    this.mobileRumSessionCountIosSum = JsonNullable.<Long>of(mobileRumSessionCountIosSum);
  }

  public UsageSummaryDateOrg mobileRumSessionCountSum(Long mobileRumSessionCountSum) {
    this.mobileRumSessionCountSum = JsonNullable.<Long>of(mobileRumSessionCountSum);
    return this;
  }

  /**
   * Shows the sum of all mobile RUM Sessions over all hours in the current date for the given org.
   *
   * @return mobileRumSessionCountSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all mobile RUM Sessions over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getMobileRumSessionCountSum() {
    return mobileRumSessionCountSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getMobileRumSessionCountSum_JsonNullable() {
    return mobileRumSessionCountSum;
  }

  @JsonProperty(JSON_PROPERTY_MOBILE_RUM_SESSION_COUNT_SUM)
  public void setMobileRumSessionCountSum_JsonNullable(
      JsonNullable<Long> mobileRumSessionCountSum) {
    this.mobileRumSessionCountSum = mobileRumSessionCountSum;
  }

  public void setMobileRumSessionCountSum(Long mobileRumSessionCountSum) {
    this.mobileRumSessionCountSum = JsonNullable.<Long>of(mobileRumSessionCountSum);
  }

  public UsageSummaryDateOrg name(String name) {
    this.name = name;
    return this;
  }

  /**
   * The organization name.
   *
   * @return name
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The organization name.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UsageSummaryDateOrg netflowIndexedEventsCountSum(Long netflowIndexedEventsCountSum) {
    this.netflowIndexedEventsCountSum = JsonNullable.<Long>of(netflowIndexedEventsCountSum);
    return this;
  }

  /**
   * Shows the sum of all Network flows indexed over all hours in the current date for the given
   * org.
   *
   * @return netflowIndexedEventsCountSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all Network flows indexed over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getNetflowIndexedEventsCountSum() {
    return netflowIndexedEventsCountSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NETFLOW_INDEXED_EVENTS_COUNT_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getNetflowIndexedEventsCountSum_JsonNullable() {
    return netflowIndexedEventsCountSum;
  }

  @JsonProperty(JSON_PROPERTY_NETFLOW_INDEXED_EVENTS_COUNT_SUM)
  public void setNetflowIndexedEventsCountSum_JsonNullable(
      JsonNullable<Long> netflowIndexedEventsCountSum) {
    this.netflowIndexedEventsCountSum = netflowIndexedEventsCountSum;
  }

  public void setNetflowIndexedEventsCountSum(Long netflowIndexedEventsCountSum) {
    this.netflowIndexedEventsCountSum = JsonNullable.<Long>of(netflowIndexedEventsCountSum);
  }

  public UsageSummaryDateOrg npmHostTop99p(Long npmHostTop99p) {
    this.npmHostTop99p = JsonNullable.<Long>of(npmHostTop99p);
    return this;
  }

  /**
   * Shows the 99th percentile of all distinct Networks hosts over all hours in the current date for
   * the given org.
   *
   * @return npmHostTop99p
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all distinct Networks hosts over all hours in the current"
              + " date for the given org.")
  @JsonIgnore
  public Long getNpmHostTop99p() {
    return npmHostTop99p.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NPM_HOST_TOP99P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getNpmHostTop99p_JsonNullable() {
    return npmHostTop99p;
  }

  @JsonProperty(JSON_PROPERTY_NPM_HOST_TOP99P)
  public void setNpmHostTop99p_JsonNullable(JsonNullable<Long> npmHostTop99p) {
    this.npmHostTop99p = npmHostTop99p;
  }

  public void setNpmHostTop99p(Long npmHostTop99p) {
    this.npmHostTop99p = JsonNullable.<Long>of(npmHostTop99p);
  }

  public UsageSummaryDateOrg opentelemetryHostTop99p(Long opentelemetryHostTop99p) {
    this.opentelemetryHostTop99p = JsonNullable.<Long>of(opentelemetryHostTop99p);
    return this;
  }

  /**
   * Shows the 99th percentile of all hosts reported by the Datadog exporter for the OpenTelemetry
   * Collector over all hours in the current date for the given org.
   *
   * @return opentelemetryHostTop99p
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all hosts reported by the Datadog exporter for the"
              + " OpenTelemetry Collector over all hours in the current date for the given org.")
  @JsonIgnore
  public Long getOpentelemetryHostTop99p() {
    return opentelemetryHostTop99p.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OPENTELEMETRY_HOST_TOP99P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getOpentelemetryHostTop99p_JsonNullable() {
    return opentelemetryHostTop99p;
  }

  @JsonProperty(JSON_PROPERTY_OPENTELEMETRY_HOST_TOP99P)
  public void setOpentelemetryHostTop99p_JsonNullable(JsonNullable<Long> opentelemetryHostTop99p) {
    this.opentelemetryHostTop99p = opentelemetryHostTop99p;
  }

  public void setOpentelemetryHostTop99p(Long opentelemetryHostTop99p) {
    this.opentelemetryHostTop99p = JsonNullable.<Long>of(opentelemetryHostTop99p);
  }

  public UsageSummaryDateOrg profilingHostTop99p(Long profilingHostTop99p) {
    this.profilingHostTop99p = JsonNullable.<Long>of(profilingHostTop99p);
    return this;
  }

  /**
   * Shows the 99th percentile of all profiled hosts over all hours in the current date for the
   * given org.
   *
   * @return profilingHostTop99p
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all profiled hosts over all hours in the current date for"
              + " the given org.")
  @JsonIgnore
  public Long getProfilingHostTop99p() {
    return profilingHostTop99p.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROFILING_HOST_TOP99P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getProfilingHostTop99p_JsonNullable() {
    return profilingHostTop99p;
  }

  @JsonProperty(JSON_PROPERTY_PROFILING_HOST_TOP99P)
  public void setProfilingHostTop99p_JsonNullable(JsonNullable<Long> profilingHostTop99p) {
    this.profilingHostTop99p = profilingHostTop99p;
  }

  public void setProfilingHostTop99p(Long profilingHostTop99p) {
    this.profilingHostTop99p = JsonNullable.<Long>of(profilingHostTop99p);
  }

  public UsageSummaryDateOrg publicId(String publicId) {
    this.publicId = publicId;
    return this;
  }

  /**
   * The organization public id.
   *
   * @return publicId
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The organization public id.")
  @JsonProperty(JSON_PROPERTY_PUBLIC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPublicId() {
    return publicId;
  }

  public void setPublicId(String publicId) {
    this.publicId = publicId;
  }

  public UsageSummaryDateOrg rumSessionCountSum(Long rumSessionCountSum) {
    this.rumSessionCountSum = JsonNullable.<Long>of(rumSessionCountSum);
    return this;
  }

  /**
   * Shows the sum of all browser RUM Sessions over all hours in the current date for the given org.
   *
   * @return rumSessionCountSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all browser RUM Sessions over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getRumSessionCountSum() {
    return rumSessionCountSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RUM_SESSION_COUNT_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getRumSessionCountSum_JsonNullable() {
    return rumSessionCountSum;
  }

  @JsonProperty(JSON_PROPERTY_RUM_SESSION_COUNT_SUM)
  public void setRumSessionCountSum_JsonNullable(JsonNullable<Long> rumSessionCountSum) {
    this.rumSessionCountSum = rumSessionCountSum;
  }

  public void setRumSessionCountSum(Long rumSessionCountSum) {
    this.rumSessionCountSum = JsonNullable.<Long>of(rumSessionCountSum);
  }

  public UsageSummaryDateOrg rumTotalSessionCountSum(Long rumTotalSessionCountSum) {
    this.rumTotalSessionCountSum = JsonNullable.<Long>of(rumTotalSessionCountSum);
    return this;
  }

  /**
   * Shows the sum of RUM Sessions (browser and mobile) over all hours in the current date for the
   * given org.
   *
   * @return rumTotalSessionCountSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of RUM Sessions (browser and mobile) over all hours in the current date"
              + " for the given org.")
  @JsonIgnore
  public Long getRumTotalSessionCountSum() {
    return rumTotalSessionCountSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RUM_TOTAL_SESSION_COUNT_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getRumTotalSessionCountSum_JsonNullable() {
    return rumTotalSessionCountSum;
  }

  @JsonProperty(JSON_PROPERTY_RUM_TOTAL_SESSION_COUNT_SUM)
  public void setRumTotalSessionCountSum_JsonNullable(JsonNullable<Long> rumTotalSessionCountSum) {
    this.rumTotalSessionCountSum = rumTotalSessionCountSum;
  }

  public void setRumTotalSessionCountSum(Long rumTotalSessionCountSum) {
    this.rumTotalSessionCountSum = JsonNullable.<Long>of(rumTotalSessionCountSum);
  }

  public UsageSummaryDateOrg syntheticsBrowserCheckCallsCountSum(
      Long syntheticsBrowserCheckCallsCountSum) {
    this.syntheticsBrowserCheckCallsCountSum =
        JsonNullable.<Long>of(syntheticsBrowserCheckCallsCountSum);
    return this;
  }

  /**
   * Shows the sum of all Synthetic browser tests over all hours in the current date for the given
   * org.
   *
   * @return syntheticsBrowserCheckCallsCountSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all Synthetic browser tests over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getSyntheticsBrowserCheckCallsCountSum() {
    return syntheticsBrowserCheckCallsCountSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SYNTHETICS_BROWSER_CHECK_CALLS_COUNT_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getSyntheticsBrowserCheckCallsCountSum_JsonNullable() {
    return syntheticsBrowserCheckCallsCountSum;
  }

  @JsonProperty(JSON_PROPERTY_SYNTHETICS_BROWSER_CHECK_CALLS_COUNT_SUM)
  public void setSyntheticsBrowserCheckCallsCountSum_JsonNullable(
      JsonNullable<Long> syntheticsBrowserCheckCallsCountSum) {
    this.syntheticsBrowserCheckCallsCountSum = syntheticsBrowserCheckCallsCountSum;
  }

  public void setSyntheticsBrowserCheckCallsCountSum(Long syntheticsBrowserCheckCallsCountSum) {
    this.syntheticsBrowserCheckCallsCountSum =
        JsonNullable.<Long>of(syntheticsBrowserCheckCallsCountSum);
  }

  public UsageSummaryDateOrg syntheticsCheckCallsCountSum(Long syntheticsCheckCallsCountSum) {
    this.syntheticsCheckCallsCountSum = JsonNullable.<Long>of(syntheticsCheckCallsCountSum);
    return this;
  }

  /**
   * Shows the sum of all Synthetic API tests over all hours in the current date for the given org.
   *
   * @return syntheticsCheckCallsCountSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all Synthetic API tests over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getSyntheticsCheckCallsCountSum() {
    return syntheticsCheckCallsCountSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SYNTHETICS_CHECK_CALLS_COUNT_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getSyntheticsCheckCallsCountSum_JsonNullable() {
    return syntheticsCheckCallsCountSum;
  }

  @JsonProperty(JSON_PROPERTY_SYNTHETICS_CHECK_CALLS_COUNT_SUM)
  public void setSyntheticsCheckCallsCountSum_JsonNullable(
      JsonNullable<Long> syntheticsCheckCallsCountSum) {
    this.syntheticsCheckCallsCountSum = syntheticsCheckCallsCountSum;
  }

  public void setSyntheticsCheckCallsCountSum(Long syntheticsCheckCallsCountSum) {
    this.syntheticsCheckCallsCountSum = JsonNullable.<Long>of(syntheticsCheckCallsCountSum);
  }

  public UsageSummaryDateOrg traceSearchIndexedEventsCountSum(
      Long traceSearchIndexedEventsCountSum) {
    this.traceSearchIndexedEventsCountSum = JsonNullable.<Long>of(traceSearchIndexedEventsCountSum);
    return this;
  }

  /**
   * Shows the sum of all Indexed Spans indexed over all hours in the current date for the given
   * org.
   *
   * @return traceSearchIndexedEventsCountSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all Indexed Spans indexed over all hours in the current date for the"
              + " given org.")
  @JsonIgnore
  public Long getTraceSearchIndexedEventsCountSum() {
    return traceSearchIndexedEventsCountSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TRACE_SEARCH_INDEXED_EVENTS_COUNT_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getTraceSearchIndexedEventsCountSum_JsonNullable() {
    return traceSearchIndexedEventsCountSum;
  }

  @JsonProperty(JSON_PROPERTY_TRACE_SEARCH_INDEXED_EVENTS_COUNT_SUM)
  public void setTraceSearchIndexedEventsCountSum_JsonNullable(
      JsonNullable<Long> traceSearchIndexedEventsCountSum) {
    this.traceSearchIndexedEventsCountSum = traceSearchIndexedEventsCountSum;
  }

  public void setTraceSearchIndexedEventsCountSum(Long traceSearchIndexedEventsCountSum) {
    this.traceSearchIndexedEventsCountSum = JsonNullable.<Long>of(traceSearchIndexedEventsCountSum);
  }

  public UsageSummaryDateOrg twolIngestedEventsBytesSum(Long twolIngestedEventsBytesSum) {
    this.twolIngestedEventsBytesSum = JsonNullable.<Long>of(twolIngestedEventsBytesSum);
    return this;
  }

  /**
   * Shows the sum of all tracing without limits bytes ingested over all hours in the current date
   * for the given org.
   *
   * @return twolIngestedEventsBytesSum
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the sum of all tracing without limits bytes ingested over all hours in the"
              + " current date for the given org.")
  @JsonIgnore
  public Long getTwolIngestedEventsBytesSum() {
    return twolIngestedEventsBytesSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TWOL_INGESTED_EVENTS_BYTES_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getTwolIngestedEventsBytesSum_JsonNullable() {
    return twolIngestedEventsBytesSum;
  }

  @JsonProperty(JSON_PROPERTY_TWOL_INGESTED_EVENTS_BYTES_SUM)
  public void setTwolIngestedEventsBytesSum_JsonNullable(
      JsonNullable<Long> twolIngestedEventsBytesSum) {
    this.twolIngestedEventsBytesSum = twolIngestedEventsBytesSum;
  }

  public void setTwolIngestedEventsBytesSum(Long twolIngestedEventsBytesSum) {
    this.twolIngestedEventsBytesSum = JsonNullable.<Long>of(twolIngestedEventsBytesSum);
  }

  public UsageSummaryDateOrg vsphereHostTop99p(Long vsphereHostTop99p) {
    this.vsphereHostTop99p = JsonNullable.<Long>of(vsphereHostTop99p);
    return this;
  }

  /**
   * Shows the 99th percentile of all vSphere hosts over all hours in the current date for the given
   * org.
   *
   * @return vsphereHostTop99p
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
      value =
          "Shows the 99th percentile of all vSphere hosts over all hours in the current date for"
              + " the given org.")
  @JsonIgnore
  public Long getVsphereHostTop99p() {
    return vsphereHostTop99p.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VSPHERE_HOST_TOP99P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Long> getVsphereHostTop99p_JsonNullable() {
    return vsphereHostTop99p;
  }

  @JsonProperty(JSON_PROPERTY_VSPHERE_HOST_TOP99P)
  public void setVsphereHostTop99p_JsonNullable(JsonNullable<Long> vsphereHostTop99p) {
    this.vsphereHostTop99p = vsphereHostTop99p;
  }

  public void setVsphereHostTop99p(Long vsphereHostTop99p) {
    this.vsphereHostTop99p = JsonNullable.<Long>of(vsphereHostTop99p);
  }

  /** Return true if this UsageSummaryDateOrg object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageSummaryDateOrg usageSummaryDateOrg = (UsageSummaryDateOrg) o;
    return Objects.equals(this.agentHostTop99p, usageSummaryDateOrg.agentHostTop99p)
        && Objects.equals(
            this.apmAzureAppServiceHostTop99p, usageSummaryDateOrg.apmAzureAppServiceHostTop99p)
        && Objects.equals(this.apmHostTop99p, usageSummaryDateOrg.apmHostTop99p)
        && Objects.equals(this.awsHostTop99p, usageSummaryDateOrg.awsHostTop99p)
        && Objects.equals(this.awsLambdaFuncCount, usageSummaryDateOrg.awsLambdaFuncCount)
        && Objects.equals(this.awsLambdaInvocationsSum, usageSummaryDateOrg.awsLambdaInvocationsSum)
        && Objects.equals(this.azureAppServiceTop99p, usageSummaryDateOrg.azureAppServiceTop99p)
        && Objects.equals(
            this.billableIngestedBytesSum, usageSummaryDateOrg.billableIngestedBytesSum)
        && Objects.equals(
            this.complianceContainerAggSum, usageSummaryDateOrg.complianceContainerAggSum)
        && Objects.equals(this.complianceHostAggSum, usageSummaryDateOrg.complianceHostAggSum)
        && Objects.equals(this.containerAvg, usageSummaryDateOrg.containerAvg)
        && Objects.equals(this.containerHwm, usageSummaryDateOrg.containerHwm)
        && Objects.equals(this.customTsAvg, usageSummaryDateOrg.customTsAvg)
        && Objects.equals(this.fargateTasksCountAvg, usageSummaryDateOrg.fargateTasksCountAvg)
        && Objects.equals(this.fargateTasksCountHwm, usageSummaryDateOrg.fargateTasksCountHwm)
        && Objects.equals(this.gcpHostTop99p, usageSummaryDateOrg.gcpHostTop99p)
        && Objects.equals(this.herokuHostTop99p, usageSummaryDateOrg.herokuHostTop99p)
        && Objects.equals(this.id, usageSummaryDateOrg.id)
        && Objects.equals(
            this.incidentManagementMonthlyActiveUsersHwm,
            usageSummaryDateOrg.incidentManagementMonthlyActiveUsersHwm)
        && Objects.equals(this.indexedEventsCountSum, usageSummaryDateOrg.indexedEventsCountSum)
        && Objects.equals(this.infraHostTop99p, usageSummaryDateOrg.infraHostTop99p)
        && Objects.equals(this.ingestedEventsBytesSum, usageSummaryDateOrg.ingestedEventsBytesSum)
        && Objects.equals(this.iotDeviceAggSum, usageSummaryDateOrg.iotDeviceAggSum)
        && Objects.equals(this.iotDeviceTop99pSum, usageSummaryDateOrg.iotDeviceTop99pSum)
        && Objects.equals(
            this.mobileRumSessionCountAndroidSum,
            usageSummaryDateOrg.mobileRumSessionCountAndroidSum)
        && Objects.equals(
            this.mobileRumSessionCountIosSum, usageSummaryDateOrg.mobileRumSessionCountIosSum)
        && Objects.equals(
            this.mobileRumSessionCountSum, usageSummaryDateOrg.mobileRumSessionCountSum)
        && Objects.equals(this.name, usageSummaryDateOrg.name)
        && Objects.equals(
            this.netflowIndexedEventsCountSum, usageSummaryDateOrg.netflowIndexedEventsCountSum)
        && Objects.equals(this.npmHostTop99p, usageSummaryDateOrg.npmHostTop99p)
        && Objects.equals(this.opentelemetryHostTop99p, usageSummaryDateOrg.opentelemetryHostTop99p)
        && Objects.equals(this.profilingHostTop99p, usageSummaryDateOrg.profilingHostTop99p)
        && Objects.equals(this.publicId, usageSummaryDateOrg.publicId)
        && Objects.equals(this.rumSessionCountSum, usageSummaryDateOrg.rumSessionCountSum)
        && Objects.equals(this.rumTotalSessionCountSum, usageSummaryDateOrg.rumTotalSessionCountSum)
        && Objects.equals(
            this.syntheticsBrowserCheckCallsCountSum,
            usageSummaryDateOrg.syntheticsBrowserCheckCallsCountSum)
        && Objects.equals(
            this.syntheticsCheckCallsCountSum, usageSummaryDateOrg.syntheticsCheckCallsCountSum)
        && Objects.equals(
            this.traceSearchIndexedEventsCountSum,
            usageSummaryDateOrg.traceSearchIndexedEventsCountSum)
        && Objects.equals(
            this.twolIngestedEventsBytesSum, usageSummaryDateOrg.twolIngestedEventsBytesSum)
        && Objects.equals(this.vsphereHostTop99p, usageSummaryDateOrg.vsphereHostTop99p);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        agentHostTop99p,
        apmAzureAppServiceHostTop99p,
        apmHostTop99p,
        awsHostTop99p,
        awsLambdaFuncCount,
        awsLambdaInvocationsSum,
        azureAppServiceTop99p,
        billableIngestedBytesSum,
        complianceContainerAggSum,
        complianceHostAggSum,
        containerAvg,
        containerHwm,
        customTsAvg,
        fargateTasksCountAvg,
        fargateTasksCountHwm,
        gcpHostTop99p,
        herokuHostTop99p,
        id,
        incidentManagementMonthlyActiveUsersHwm,
        indexedEventsCountSum,
        infraHostTop99p,
        ingestedEventsBytesSum,
        iotDeviceAggSum,
        iotDeviceTop99pSum,
        mobileRumSessionCountAndroidSum,
        mobileRumSessionCountIosSum,
        mobileRumSessionCountSum,
        name,
        netflowIndexedEventsCountSum,
        npmHostTop99p,
        opentelemetryHostTop99p,
        profilingHostTop99p,
        publicId,
        rumSessionCountSum,
        rumTotalSessionCountSum,
        syntheticsBrowserCheckCallsCountSum,
        syntheticsCheckCallsCountSum,
        traceSearchIndexedEventsCountSum,
        twolIngestedEventsBytesSum,
        vsphereHostTop99p);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageSummaryDateOrg {\n");
    sb.append("    agentHostTop99p: ").append(toIndentedString(agentHostTop99p)).append("\n");
    sb.append("    apmAzureAppServiceHostTop99p: ")
        .append(toIndentedString(apmAzureAppServiceHostTop99p))
        .append("\n");
    sb.append("    apmHostTop99p: ").append(toIndentedString(apmHostTop99p)).append("\n");
    sb.append("    awsHostTop99p: ").append(toIndentedString(awsHostTop99p)).append("\n");
    sb.append("    awsLambdaFuncCount: ").append(toIndentedString(awsLambdaFuncCount)).append("\n");
    sb.append("    awsLambdaInvocationsSum: ")
        .append(toIndentedString(awsLambdaInvocationsSum))
        .append("\n");
    sb.append("    azureAppServiceTop99p: ")
        .append(toIndentedString(azureAppServiceTop99p))
        .append("\n");
    sb.append("    billableIngestedBytesSum: ")
        .append(toIndentedString(billableIngestedBytesSum))
        .append("\n");
    sb.append("    complianceContainerAggSum: ")
        .append(toIndentedString(complianceContainerAggSum))
        .append("\n");
    sb.append("    complianceHostAggSum: ")
        .append(toIndentedString(complianceHostAggSum))
        .append("\n");
    sb.append("    containerAvg: ").append(toIndentedString(containerAvg)).append("\n");
    sb.append("    containerHwm: ").append(toIndentedString(containerHwm)).append("\n");
    sb.append("    customTsAvg: ").append(toIndentedString(customTsAvg)).append("\n");
    sb.append("    fargateTasksCountAvg: ")
        .append(toIndentedString(fargateTasksCountAvg))
        .append("\n");
    sb.append("    fargateTasksCountHwm: ")
        .append(toIndentedString(fargateTasksCountHwm))
        .append("\n");
    sb.append("    gcpHostTop99p: ").append(toIndentedString(gcpHostTop99p)).append("\n");
    sb.append("    herokuHostTop99p: ").append(toIndentedString(herokuHostTop99p)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    incidentManagementMonthlyActiveUsersHwm: ")
        .append(toIndentedString(incidentManagementMonthlyActiveUsersHwm))
        .append("\n");
    sb.append("    indexedEventsCountSum: ")
        .append(toIndentedString(indexedEventsCountSum))
        .append("\n");
    sb.append("    infraHostTop99p: ").append(toIndentedString(infraHostTop99p)).append("\n");
    sb.append("    ingestedEventsBytesSum: ")
        .append(toIndentedString(ingestedEventsBytesSum))
        .append("\n");
    sb.append("    iotDeviceAggSum: ").append(toIndentedString(iotDeviceAggSum)).append("\n");
    sb.append("    iotDeviceTop99pSum: ").append(toIndentedString(iotDeviceTop99pSum)).append("\n");
    sb.append("    mobileRumSessionCountAndroidSum: ")
        .append(toIndentedString(mobileRumSessionCountAndroidSum))
        .append("\n");
    sb.append("    mobileRumSessionCountIosSum: ")
        .append(toIndentedString(mobileRumSessionCountIosSum))
        .append("\n");
    sb.append("    mobileRumSessionCountSum: ")
        .append(toIndentedString(mobileRumSessionCountSum))
        .append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    netflowIndexedEventsCountSum: ")
        .append(toIndentedString(netflowIndexedEventsCountSum))
        .append("\n");
    sb.append("    npmHostTop99p: ").append(toIndentedString(npmHostTop99p)).append("\n");
    sb.append("    opentelemetryHostTop99p: ")
        .append(toIndentedString(opentelemetryHostTop99p))
        .append("\n");
    sb.append("    profilingHostTop99p: ")
        .append(toIndentedString(profilingHostTop99p))
        .append("\n");
    sb.append("    publicId: ").append(toIndentedString(publicId)).append("\n");
    sb.append("    rumSessionCountSum: ").append(toIndentedString(rumSessionCountSum)).append("\n");
    sb.append("    rumTotalSessionCountSum: ")
        .append(toIndentedString(rumTotalSessionCountSum))
        .append("\n");
    sb.append("    syntheticsBrowserCheckCallsCountSum: ")
        .append(toIndentedString(syntheticsBrowserCheckCallsCountSum))
        .append("\n");
    sb.append("    syntheticsCheckCallsCountSum: ")
        .append(toIndentedString(syntheticsCheckCallsCountSum))
        .append("\n");
    sb.append("    traceSearchIndexedEventsCountSum: ")
        .append(toIndentedString(traceSearchIndexedEventsCountSum))
        .append("\n");
    sb.append("    twolIngestedEventsBytesSum: ")
        .append(toIndentedString(twolIngestedEventsBytesSum))
        .append("\n");
    sb.append("    vsphereHostTop99p: ").append(toIndentedString(vsphereHostTop99p)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
